<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?=$this->tr('resume_preview')?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="/css/default/usr/css.css" rel="stylesheet" type="text/css" />
	<style type="text/css">
		body {
			width:960px;
			margin:0 auto;
			margin-bottom:10px;
			text-align:left;
			font-size: 10px;			
		}
	</style>
</head>
<body>
<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
	<div id="wraper" style="position:absolute;">
		<!-- 右上角按钮：打印，下载 -->
		<div style="text-align: right; margin: 0 10px 0 0;">
			<img alt="Print" src="/img/default/print_ico.gif" />
			<a href="javascript:void(0);" id="btn_print_resume" style="margin-left:0;">
				<span style="vertical-align: super;"><?=$this->tr('PRINT')?></span>
			</a>
		</div>
		<!-- 状态信息 -->
		<div style="background-color: #d9ffff;">
			<div style="font-weight: bold;"><?=$this->tr('STATUS_INFO')?></div>
			<div><?=$this->tr('ABLE_WORK_DATE')?>：
				<?=$this->tr($this->resume['able_work_date_choice'])?>
				&nbsp;&nbsp;
				<?php if ($this->resume['able_work_date'] != '0000-00-00'):?>
					<?=$this->resume['able_work_date']?>
				<?php endif;?>
			</div>
			<div><?=$this->tr('current_biz_state')?>：<?=$this->tr('IS_APPLY_PRJ_' . $this->resume['is_apply_prj'])?></div>
		</div>
		<!-- 简历基本信息、业务经历、项目经验 -->
		<!--printBegin-->
		<?php include_once 'previewresumebaseinfo.phtml';?>
		<?php include_once 'previewresumebiz.phtml';?>
		<?php include_once 'previewresumeprj.phtml';?>
		<!--printEnd-->
	</div>
	<div><img alt="" src="/img/default/usr/<?=$auth->locale?>/bg_preview_rsm.png" /></div>
<?if(isset($this->caseCode) && !empty($this->caseCode)):?>
	<div align="center">
		<input type="image" src="/img/default/front/<?=$auth->locale?>/btn_alter.jpg" id="editBtn"/>
		<input type="image" src="/img/default/front/<?=$auth->locale?>/btn_offer.jpg" id="applyBtn"/>
	</div>
	
	<script type="text/javascript">
		/*
		 * 修改简历
		 */
		$('#editBtn').click(function() {
			window.location.href = "/usr_resume/modifyresume/resumeCode/<?=$this->resume['code']?>/anchor/baseinfo";
		});
		
		
		/**
		 * 应聘案件
		 */
		$('#applyBtn').click(function() {
			window.location.href = "/front_case/casedetail/caseCode/<?=$this->caseCode?>/btnlist/submit";
		});
	</script>
<?endif;?>
	
	<script type="text/javascript">
		//简历信息
		var usr = <?=json_encode($this->usr)?>;
		var resume = <?=json_encode($this->resume)?>;
		var resumeBizs = <?=json_encode($this->resumeBizs)?>;
		var resumePrjs = <?=json_encode($this->resumePrjs)?>;
		var YEAR_1 = '<?=$this->tr('1_YEAR')?>';
		var YEAR_2 = '<?=$this->tr('2_YEAR')?>';
		var YEAR_3 = '<?=$this->tr('3_YEAR')?>';
		var YEAR_4 = '<?=$this->tr('4_YEAR')?>';
		var YEAR_5 = '<?=$this->tr('5_YEAR')?>';
		var YEAR_6 = '<?=$this->tr('6_YEAR')?>';
		var YEAR_7 = '<?=$this->tr('7_YEAR')?>';
		var YEAR_8 = '<?=$this->tr('8_YEAR')?>';
		var YEAR_9 = '<?=$this->tr('9_YEAR')?>';
	</script>
	<script src="/js/jquery/jquery-1.7.2.js" type="text/javascript"></script>
	<script src="/js/util.js" type="text/javascript"></script>
	<script type="text/javascript" src="/js/default/usr/resume/previewresume.js"></script>
	<script type="text/javascript" src="/js/default/usr/resume/previewresumebaseinfo.js"></script>
	<script type="text/javascript" src="/js/default/usr/resume/previewresumebiz.js"></script>
	<script type="text/javascript" src="/js/default/usr/resume/previewresumeprj.js"></script>
</body>
</html>
