<form id="form_resumeBaseInfo" name="form_resumeBaseInfo" method="post" action="">
<div class="resume_t">
	<span style="font-size: 32px;">
		<? echo $this->tr('POS'), $this->tr('EXPERIENCE2'), $this->tr('BOOK')?>
	</span>	
	<div class="resume_date" style="text-align: right; margin-right: 10px;">
		<div><?=$this->tr('DATE')?>：<?=date('Y-m-d')?></div>
	</div>
</div>
<div class="resume_base_info">
	  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_resume" align="center">
        <tr>
          <th width="10%" align="center" bgcolor="#d9ffff"> <?=$this->tr('FULLNAME_PINYIN')?></th>
          <td style="width: 15%; text-align: center;">&nbsp;<?=$this->resume['fullname_p']?></td>
          <th width="10%" align="center" bgcolor="#d9ffff"><?=$this->tr('SEX__')?></th>
          <th width="15%" align="center" bgcolor="#d9ffff"><span id="label_birthday"><?=$this->tr('BIRTHDAY')?></span></th>
          <th width="14%" align="center" bgcolor="#d9ffff"><?=$this->tr('LANG_ABILITY')?>(<span class="fred"><?=$this->tr('NOTE')?>１</span>)</th>
          <th width="4%" align="center" bgcolor="#d9ffff" class="line-dot">A</th>
          <th width="4%" align="center" bgcolor="#d9ffff" class="line-dot">B</th>
          <th width="4%" align="center" bgcolor="#d9ffff" class="line-dot">C</th>
          <th width="4%" align="center" bgcolor="#d9ffff" class="line-dot">D</th>
          <th width="4%" align="center" bgcolor="#d9ffff">E</th>
          <th width="10%" align="center" bgcolor="#d9ffff">&nbsp;<?=$this->tr('QUALIFICATION')?></th>
        </tr>
        <tr>
          <th rowspan="2" align="center" bgcolor="#d9ffff">&nbsp;<span id="label_fullname"><?=$this->tr('NAME')?></span></th>
          <td rowspan="2" align="center" style="font-size: 24px;">&nbsp;<?=$this->resume['fullname']?></td>
          <td rowspan="2" align="center" >&nbsp;<?=$this->tr($this->resume['sex'])?></td>
          <td align="center" >&nbsp;<? echo ($this->resume['birthday'] != '0000-00-00')? $this->resume['birthday'] : ''?>
          </td>
          <th align="center" bgcolor="#D9FFFF">&nbsp;<span id="label_jaAbility"><?=$this->tr('JAPANESE')?></span></th>
          <td align="center" class="line-dot" >&nbsp;<span id="jaAbility_A" style="display: none;">●</span></td>
          <td align="center" class="line-dot" >&nbsp;<span id="jaAbility_B" style="display: none;">●</span></td>
          <td align="center" class="line-dot" >&nbsp;<span id="jaAbility_C" style="display: none;">●</span></td>
          <td align="center" class="line-dot" >&nbsp;<span id="jaAbility_D" style="display: none;">●</span></td>
          <td align="center" >&nbsp;<span id="jaAbility_E" style="display: none;">●</span></td>
          <td align="center" >&nbsp;<?=$this->tr('ABOVE_LEVEL_' . $this->resume['ja_qualification'])?></td>
        </tr>
        <tr>
          <td align="center" >&nbsp;<?=$this->tr('FULL')?><span id="fullAge"></span><?=$this->tr('YEARS_OLD')?></td>
          <th align="center" bgcolor="#D9FFFF">&nbsp;<?=$this->tr('ENGLISH')?></th>
          <td align="center"  class="line-dot">&nbsp;<span id="enAbility_A" style="display: none;">●</span></td>
          <td align="center"  class="line-dot">&nbsp;<span id="enAbility_B" style="display: none;">●</span></td>
          <td align="center"  class="line-dot">&nbsp;<span id="enAbility_C" style="display: none;">●</span></td>
          <td align="center"  class="line-dot">&nbsp;<span id="enAbility_D" style="display: none;">●</span></td>
          <td align="center" >&nbsp;<span id="enAbility_E" style="display: none;">●</span></td>
          <td align="center" >&nbsp;<?=$this->tr('ABOVE_LEVEL_' . $this->resume['en_qualification'])?></td>
        </tr>
        <tr>
          <th align="center" bgcolor="#d9ffff">&nbsp;<?=$this->tr('BIRTHPLACE')?></th>
          <td align="left">&nbsp;<?=$this->resume['birthplace']?></td>
          <th align="center" bgcolor="#D9FFFF"><?=$this->tr('MARRIAGE_STATUS')?></th>
          <td align="center" >&nbsp;<?php if ($this->resume['marital'] == 'Y'):?>          		<?=$this->tr('MARRIED')?>
          	<?php elseif ($this->resume['marital'] == 'N'):?>
          		<?=$this->tr('UNMARRIED')?>
          	<?php endif;?>
          </td>
          <th align="center" bgcolor="#D9FFFF">
          	<span id="label_tel"><?=$this->tr('TEL')?></span>
          </th>
          <td colspan="6" align="left" >&nbsp;
          	<?=$this->resume['tel']?>
          </td>
        </tr>
        <tr>
          <th align="center" bgcolor="#d9ffff"><?=$this->tr('ACTUAL_RESIDENCE')?></th>
          <td align="left" colspan="3" >&nbsp;
            <?=$this->tr($this->resume['actual_residence_province'])?>
		  	<?=$this->resume['actual_residence']?>
		  </td>
          <th align="center" bgcolor="#D9FFFF"><span id="label_email">E-Mail</span></th>
          <td colspan="6" align="left" >&nbsp;
          	<?=$this->resume['email']?>
          </td>
        </tr>
        <tr>
          <th align="center" bgcolor="#d9ffff"><?=$this->tr('NEAREST_STATION')?></th>
          <td align="left" >&nbsp;
          	<?=$this->resume['nearest_station']?>
          </td>
          <th align="center" bgcolor="#D9FFFF">
          	<span id="label_nationality"><?=$this->tr('NATIONALITY')?></span>
          </th>
          <td align="left" >&nbsp;
            <?=$this->tr($this->resume['nationality'])?>
          </td>
          <th align="center" bgcolor="#D9FFFF"><?=$this->tr('YEAR_ARRIVE_JP')?></th>
          <td colspan="6" align="left">&nbsp;
          	<?=$this->resume['date_arrive_jp'] != '0000-00-00' ? $this->resume['date_arrive_jp'] : ''?>
          </td>
        </tr>
        <tr>
          <th align="center" bgcolor="#d9ffff"><?=$this->tr('FINAL_DEGREE')?></th>
          <td align="left" >&nbsp;
          	<?=$this->resume['final_degree']?>
          </td>
          <th align="center" bgcolor="#D9FFFF"><?=$this->tr('SUBJECT')?></th>
          <td align="left" >&nbsp;
          	<?=$this->resume['major']?>
          </td>
          <th align="center" bgcolor="#D9FFFF"><?=$this->tr('GRADUATE_YEAR')?></th>
          <td colspan="6" align="left">&nbsp;
          	<?=$this->resume['date_graduate'] != '0000-00-00' ? $this->resume['date_graduate'] : ''?>
          </td>
        </tr>
        <tr>
          <th align="center" bgcolor="#d9ffff"><?=$this->tr('KINDS_OF_SKILLS')?></th>
          <td align="left" colspan="10" >&nbsp;
          	<?=$this->resume['skill']?>
          </td>
        </tr>
        <tr>
          <th align="center" valign="top" bgcolor="#d9ffff"><?=$this->tr('PERSONAL_PR')?></th>
          <td align="left" colspan="10" >&nbsp;
            <?=$this->resume['pr']?>
          </td>
        </tr>
      </table>
	</div>
	<div align="left" class="conU"><span class="fred"><?=$this->tr('NOTE')?>１：</span><?=$this->tr('LANG_ABILITY')?>　
		A:<?=$this->tr('NATIVE_LANG_EQUAL')?>　　B:<?=$this->tr('BIZ_EXCHANGE')?>　　
		C:<?=$this->tr('EVERYDAY_CONVERSATION')?>　　D:<?=$this->tr('NECESSARY_CONVERSATION')?>　　
		E:<?=$this->tr('UNKNOWN')?>
	</div>
</form>