<style type="text/css">
	div {margin-top: 20px;}
</style>


<!-- tip -->
<div class="tip" id="tip_sys"></div>

<!-- 清空Memcache -->
<div>
	<a href="javascript:void(0);" id="btn_flushMc">清空Memcache</a>
</div>


<!-- 清空资源 -->
<div>
	<a href="javascript:void(0);" id="btn_clearRscs">清空资源和权限</a>
</div>


<!-- 搜索并保存所有资源 -->
<div>
	<a href="javascript:void(0);" id="btn_searchAndSaveRsc">搜索并保存所有资源及权限</a>
</div>


<!-- 将管理员发送给法人、用户或营业员的消息，再通过邮件发送 -->
<div>
	<a href="javascript:void(0);" id="btn_adminSendMail">管理员将消息通过邮件发送</a>
</div>


<!-- 以下两个从php中，直接执行Linux shell文件不成功 -->
<!-- 在日本VPS上，从中国VPS恢复数据库 -->
<!--<div>-->
<!--	<a href="javascript:void(0);" id="btn_recoverDbFromCn">从中国VPS恢复数据库</a>-->
<!--</div>-->


<!-- 备份数据库 -->
<div>
	<a href="javascript:void(0);" id="btn_backupDb">备份数据库</a>
</div>


<script type="text/javascript">
	var CONFIRM_DEL = '<? echo $this->tr('CONFIRM'), $this->tr('DEL')?>';
</script>
<script src="/js/admin/sys/sys.js" type="text/javascript"></script>