<link href="/css/default/usr/css.css" rel="stylesheet" type="text/css" />

<div class="subnav">
	<a href="/usr_usr/usr" target="_blank">
		<img src="/img/default/usr/<?=$auth->locale?>/subnav_t.jpg" width="128" height="41" border="0" class="subnav_t" />
	</a>
	<div class="subnav_c">
		<ul class="dropdown">
			<li><a href="/usr_usr/baseinfo" class="on" target="_self"><?=$this->tr('base_info_p_menu')?></a></li>
			<li><a href="/msg_msg/msg" target="_self"><?=$this->tr('msg_notify_p_menu')?></a></li>
			<li><a href="/usr_caseapply/applycaselist" target="_self"><?=$this->tr('apply_case_list_p_menu')?></a></li>
			<li><a href="/usr_casecollect/comcollectcaselist" target="_self"><?=$this->tr('com_collect_case_list_p_menu')?></a></li>
			<li><a href="/usr_caseapply/historyapplycaselist" target="_self"><?=$this->tr('apply_case_list_history_p_menu')?></a></li>
			<li><a href="/usr_casecollect/incollectcaselist" target="_self"><?=$this->tr('interest_case_list_p_menu')?></a></li>
			<li><a href="/usr_event/initiateevent" target="_self"><?=$this->tr('create_envent_list_p_menu')?></a></li>
			<li><a href="/usr_event/joineventlist" target="_self"><?=$this->tr('join_event_list_p_menu')?></a></li>
		</ul>
	</div>
</div>

<!--script type="text/javascript" src="/js/jquery/jquery.dropdown.js"></script>-->