<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>
<div id="wraper">
	<h3 class="t_top">活动留言维护页面</h3>	
	<form id="form1" name="form1" method="post" action="">
	<div class="marB">请维护下面留言</div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_faren_list">
    <tr>
      <th width="10%" align="center">活动编号</th>
      <th width="73%" align="left">留言内容</th>
      <th width="17%" align="center">操作</th>
      </tr>
    <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
	  <tr>
      <td align="center">0001</td>
      <td align="left">显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字显示30个字</td>
      <td align="center"><a href="#" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_del_little.jpg" width="50" height="20" /></a></td>
      </tr>
  </table>
  <div class="btn_os">
<div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
</form>
</div>