<div id="wraper">
<?php include_once 'inc/centerheader.phtml';?>
<h3 class="msg_title"><?=$this->tr("apply_mgt")?></h3>
<div class="faren-apply_detail">
<h2 class="case_lie02_t"><span class="skim_num"><?=$this->tr("viewers")?><?=$this->case['viewers']?><?=$this->tr("unit_person")?></span><?=$this->case['name']?></h2>
<ul class="case_lie02_time">
	<li><?=$this->tr("case_release_date")?>：<?=substr($this->case["release_date"],0,10)?></li>
	<li><?=$this->tr("case_timeliness")?>：<?=$this->case["timeliness"]?><?=$this->tr("case_release_date_till")?></li>
	<li><?=$this->tr("case_lp_code")?>：<?=$this->case["lp_code"]?></li>
	<li><?=$this->tr("case_lp_name")?>：<?=$this->case["lp_name"]?></li>
</ul>
<div class="case_lie02_con">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
	<tr valign="top">
		<td>【<?=$this->tr("case_business_req")?>】</td><td colspan="3"><?=nl2br($this->case["business_req"])?></td>
	</tr><tr valign="top">
		<td>【<?=$this->tr("case_technical_req")?>】</td><td colspan="3"><?=nl2br($this->case["technical_req"])?></td>
	</tr><tr>
		<td width="9%">【<?=$this->tr("case_jpl")?>】</td><td width="31%"><?=$this->case["jplValue"]?></td>
		<td width="9%">【<?=$this->tr("case_interview")?>】</td><td width="51%"><?=$this->case["interviewerValue"]?></td>
	</tr><tr>
		<td>【<?=$this->tr("case_case_range")?>】</td><td><?=$this->case["caseRangeValue"]?></td>
		<td>【<?=$this->tr("case_age_reg")?>】</td><td><?=$this->case["ageReqValue"]?></td>
	</tr><tr>
		<td>【<?=$this->tr("case_end_range")?>　　】</td><td><?=$this->case["period"]?></td>
		<td>【<?=$this->tr("case_country_req")?>】</td><td><?=$this->case["countryReqValue"]?> </td>
	</tr><tr>
		<td>【<?=$this->tr("case_delay")?>】</td><td><?=$this->case["delayValue"]?></td>
		<td>【<?=$this->tr("case_unit_price")?>　　】</td><td><?=$this->case["unitPriceValue"]?></td>
	</tr><tr>
		<td>【<?=$this->tr("case_working_place")?>】</td><td><?=$this->case["workingPlaceValue"]?> </td>
		<td>【<?=$this->tr("case_overtime_pay")?>　　】</td><td><?=$this->case["overtimePayValue"]?></td>
	</tr>
</table>
</div>
</div>

<div class="judge_t"><strong><?=$this->tr("lp_interview_result")?></strong></div>
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_judge" id="tab_list">
	<thead><tr>
		<th width="36%" align="left"><?=$this->tr("baseinfo")?></th>
		<th width="9%"><?=$this->tr('RESULT')?></th>
		<th width="10%"><?=$this->tr("reason")?></th>
		<th width="15%" style="text-align:center"><?=$this->tr("admission_date")?></th>
		<th width="10%" style="text-align:center"><?=$this->tr("admission_place")?></th>
		<th width="10%" style="text-align:center"><?=$this->tr("linkman")?></th>
		<th width="10%" style="text-align:center"><?=$this->tr("telephone")?></th>
	</tr></thead>
	<tbody>
	<?if (isset($this->usrInfoList)): foreach ($this->usrInfoList as $usr):?>
	<tr>
		<td align="left"><?=$usr["baseinfo"]?></td>
		<td align="center">
			<select name="result" class="myselect_result">
				<option value="OK" <?if(isset($usr['admission_result']) && $usr['admission_result']=='OK'):?>selected<?endif;?>>OK</option>
				<option value="NG" <?if(isset($usr['admission_result']) && $usr['admission_result']=='NG'):?>selected<?endif;?>>NG</option>
			</select>
		</td>
		<?
			$okHide = !isset($usr['admission_result']) || $usr['admission_result']=='OK' ? 'style="display:none;"' : '';
		  	$ngHide = isset($usr['admission_result']) && $usr['admission_result']=='NG' ? 'style="display:none;"' : '';
		?>
		<td align="center">
		<select name="NGReason" class="cancel_select" <?=$okHide;?>>
			<? if (isset ($this->cancelReasons)) : foreach ($this->cancelReasons as $reasonName => $reasonValue) : ?>
	          	<option value="<?=$reasonName?>" <?if(isset($usr['admission_result']) && $usr['admission_result']=='NG' && $usr['admission_reason']==$reasonName):?>selected<?endif;?>><?=$reasonValue?></option>
            <? endforeach; endif; ?>
		</select></td>
		<td align="center"><input class="Wdate" type="text" name="admission_date" <?=$ngHide;?>  value="<?=isset($usr['admission_date'])?$usr['admission_date']:''?>"></td>
		<td align="center"><input type="text" name="admission_place" class="myinput_baseinfo" <?=$ngHide;?>  value="<?=isset($usr['admission_place'])?$usr['admission_place']:''?>"/></td>
		<td align="center"><input type="text" name="admission_linkman" class="myinput_baseinfo" <?=$ngHide;?>  value="<?=isset($usr['admission_linkman'])?$usr['admission_linkman']:''?>"/></td>
		<td align="center">
			<input type="text" name="admission_telephone" class="myinput_baseinfo" <?=$ngHide;?> value="<?=isset($usr['admission_telephone'])?$usr['admission_telephone']:''?>"/>
			<input type="hidden" name="applyId" value="<?=$usr['apply_id']?>"/>
		</td>
    </tr>
	<?endforeach;endif;?>
	</tbody>
</table>
<div class="btn_os">
  <input type="image" id="btn_confirm" src="/img/default/front/<?=$auth->locale?>/btn_qd.jpg" class="marR" />
</div>
</div>

<form action="" method="post" id="dynForm" style="display:none;">
<input id="usrInfoList" name="usrInfoList"/>
<input id="usrList" name="usrList" value='<?=$this->usrList?>'/>
<input type="hidden" id="case" name="case" value='<?=json_encode($this->case)?>'/>
</form>
<script src="/js/default/lp/interview/interviewresultinform.js" type="text/javascript"></script>
