<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>
<div id="wraper">
	<h3 class="t_top">管理员案件统计</h3>
	<form id="form2" name="form2" method="post" action="">
	<div class="top_search_nobg">
	
	<ul>
	<li><img src="/img/admin/<?=$auth->locale?>/icon_search.gif" width="28" height="23" /></li>
	<li>时间段搜索 <label><input type="text" class="Wdate" onClick="WdatePicker()" ></label></li>
	<li>到 <label><input type="text" class="Wdate" onClick="WdatePicker()" ></label></li>
	<li><label><input type="image" name="imageField3" src="/img/default/front/<?=$auth->locale?>/btn_qd.jpg" /></label></li>
	<li><label><input name="textfield6" type="text" class="myinput" size="30"  /></label></li>
	<li><label><input type="image" name="imageField3" src="/img/default/front/<?=$auth->locale?>/btn_blur_search.jpg" /></label></li>
	</ul>
	</div> 
 <div id="tab3">
	<ul>
	<li onclick="setTab(3,0)" class="now">成功案件(20)</li>
	<li onclick="setTab(3,1)">失败案件(4)</li>
	<li onclick="setTab(3,2)">应征中(20)</li>
	<li onclick="setTab(3,3)">管理员未处理(20)</li>
	<li onclick="setTab(3,4)">管理员处理(20)</li>
	<li onclick="setTab(3,5)">面试调整中(20)</li>
	<li onclick="setTab(3,6)">面试决定(20)</li>
	<li onclick="setTab(3,7)">面试合格(20)</li>
	</ul>
	</div>
	<div id="tablist3">
	<div class="tablist block">	
		  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>	
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os"><div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	<div class="tablist">
	<table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_apply_01" class="tab_search_list">
			<tr>
			  <th width="19%" align="center">案件名</th>
			  <th width="13%" align="center">发布公司ID</th>
			  <th width="24%" align="center">发布公司名</th>
		      <th width="13%" align="center">发布时间</th>
			  <th width="12%" align="center">开始时间</th>
			  <th width="11%" align="center">场 所</th>
			  <th width="8%" align="center">合格人数</th>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
			<tr>
			  <td align="center">证券开发1</td>
			  <td align="center">COM12345</td>
			  <td align="center">红星股份</td>
		      <td align="center">2012-1-2</td>
			  <td align="center">2012-1-2</td>
			  <td align="center"> 东京，木场</td>
			  <td align="center">40</td>
			</tr>
		  </table>
		  <div class="btn_os">
		  	<div class="page"><span class="page_num">总共 880条记录   2/20</span>
		  		<span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
			</div>
	</div>
	</div>
</form>
</div>