<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<div id="wraper">
<div id="left">
	<form id="dynForm" name="dynForm" method="post" action="">
	<div class="case_search">
		<span class="search_t"><img src="/img/default/front/<?=$auth->locale?>/search_t.jpg" width="107" height="43" /></span>
		<div class="conU">
		<label><select name="range" id="range" class="search_sort_select">
			<option value="case_name"><?=$this->tr("case_name")?></option>
			<option value="case_id"><?=$this->tr("case_id")?></option>
			<option value="lp_id"><?=$this->tr("COM_ID")?></option>
			<option value="LP_NAME"><?=$this->tr("COM_NAME")?></option>
		</select></label>
		<label><input type="text" id="casename" name="casename" class="myinput" /></label>
		<label><input alt="Search" type="image" id="btn_search" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" class="mybtn" />
		</label>
		</div>
	</div>
	<div class="case_search">
		<h4 class="case_search_title"><?=$this->tr("please_choice_case_type")?></h4>
		<div class="case_search_con">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr><td><label>
				<input type="radio" name="casetype" value="cases_all" checked/>
			</label> <?=$this->tr("cases_all")?></td>
			<td><label>
                <input type="radio" name="casetype" value="cases_new" />
			</label> <?=$this->tr("cases_new")?></td>
			<td><label>
				<input type="radio" name="casetype" value="cases_recommend" />
			</label> <?=$this->tr("cases_recommend")?></td></tr>
		</table></div>
		
		<h4 class="case_search_title"><?=$this->tr("please_choice_careers")?></h4>
		<div class="case_search_con">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr>
			<?php $idx = 1; if (isset($this->careers)) : foreach ($this->careers as $careerName => $careerValue):?>
				<td width="33%"><label>
          		<input type="checkbox" name="careers[]" value="<?=$careerName?>" />
				<?=$careerValue?></label></td>
	          	<?php if ($idx++%3 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr>
		</table></div>
		
		<div style="clear: both;"></div>
		<div class="fl w01">
		<h4 class="case_search_title"><?=$this->tr("please_choice_languages")?></h4>
		<div class="case_search_con">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr>
			<?php $idx = 1; if (isset($this->languages)) : foreach ($this->languages as $languagesName => $languagesValue):?>
				<td width="50%"><label>
          		<input type="checkbox" name="languages[]" value="<?=$languagesName?>" />
	          	<?=$languagesValue?></label></td>
	          	<?php if ($idx++%2 == 0) :?>
	          		</tr><tr>
	          	<?php endif;?>
			<?php endforeach;endif;?>
			</tr>
		</table></div></div>
		
		<div class="fr w02">
		<h4 class="case_search_title"><?=$this->tr("please_choice_industries")?></h4>
		<div class="case_search_con">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr>
            <?php $idx = 1; if (isset($this->industries)) : foreach ($this->industries as $industriesName => $industriesValue):?>
	          	<td width="50%"><label>
	          		<input type="checkbox" name="industries[]" value="<?=$industriesName?>" />
	          	<?=$industriesValue?></label></td>
	          	<?php if ($idx++%2 == 0) :?>
	          		</tr><tr>
	          	<?php endif;?>
			<?php endforeach;endif;?>
			</tr>
		</table></div></div>
		
		<div style="clear: both;"></div>
		<h4 class="case_search_title"><?=$this->tr("please_choice_workingplace")?></h4>
		<div class="address_t">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr><td>
				<input type="checkbox" name="japans" value="all" class="japan" />
				<?=$this->tr("Japan")?>
			</td></tr></table>
		</div>
		<div class="address_con">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
		  	<tr>
			<?php $idx = 1; if (isset($this->japan)) : foreach ($this->japan as $name => $value):?>
				<td width="20%"><label>
				<input type="checkbox" name="workplace[]" class="japanlist" value="<?=$name;?>" />
				<?=$value?></label></td>
	          	<?php if ($idx++%5 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr></table>
		</div>
		<div class="address_t">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr><td>
            	<input type="checkbox" name="overseas" value="all" class="over" />
              	<?=$this->tr("OVERSEA")?>
			</td></tr></table>
		</div>
		<div class="address_con">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
			<?php $idx = 1; if (isset($this->oversea)) : foreach ($this->oversea as $name => $value):?>
				<td width="20%"><label>
				<input type="checkbox" name="workplace[]" class="overlist" value="<?=$name;?>" />
				<?=$value?></label></td>
	          	<?php if ($idx++%5 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr></table>
		</div>
		<!-- <h4 class="case_search_title"><?=$this->tr("case_startdate")?></h4>
		<div class="case_search_con">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr><td width="22%">
                <input type="radio" name="radiobutton" value="1" checked/>
				<?=$this->tr("case_current_date")?>
			</td><td>
                <input type="radio" name="radiobutton" value="2" />
				<input class="Wdate" type="text" name="startDate" readonly> ～ <input class="Wdate" type="text" name="endDate" readonly></td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title"><?=$this->tr("case_unit_price")?></h4>
		<div class="case_search_con">
			<input type="text" name="unitprice" class="price" " />
			<?=$this->tr("unit_price_above")?>
		</div>
		<div class="case_search_lie">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr><td>
                <input type="checkbox" name="checkbox" value="checkbox" />
 				<?=$this->tr("interview_has_long")?>
 			</td></tr></table>
		</div> -->
		<div class="btn_search">
			<input alt="Search" id="btn_search_advanced" src="/img/default/front/<?=$auth->locale?>/btn_search.jpg" type="image" width="191" height="38" border="0" />
		</div>
	</div></form>
</div>
<!--	<div id="right">-->
<!--	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>-->
<!--	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>-->
<!--	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>-->
<!--	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>-->
<!--	<div style="height:160px; background-color:#e9e9e9;"></div>-->
<!--	</div>-->
<div style="clear: both;"></div>
</div>
<script type="text/javascript">
var orgSearchFields = <?=json_encode($this->orgSearchFields)?>
</script>
<script type="text/javascript" src="/js/admin/admin/case/casesearch.js"></script>