<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>
<div id="wraper">
	<h3 class="t_top">法人点数历史</h3>
	<div class="top_search_nobg">
	<form id="form2" name="form2" method="post" action="">
	<ul>
	<li>区间：</li>
	<li><label><input type="text" name="textfield" class="myinput" /></label></li>
	<li> ～</li>
	<li><label><input type="text" name="textfield" class="myinput" /></label></li>
	<li>服务：</li>
	<li><label><select name="select" class="myselect">
	  <option>用户信息查看服务</option>
	  <option>点数购买</option>
	</select></label></li>
	<li><label><input type="image" name="imageField3" src="/img/default/front/<?=$auth->locale?>/btn_cx.gif" /></label></li>
	<li><img src="/img/default/front/<?=$auth->locale?>/btn_rujin.jpg" width="84" height="26" /></li>
	</ul>
	</form>
  </div>
  <div class="consume-record">剩余点数:200</div>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_faren_list">
    <tr>
      <th width="6%" align="center">日期</th>
      <th width="10%" align="center">分类</th>
      <th width="8%" align="center">点数</th>
      <th width="7%">剩余</th>
      <th width="10%">用途</th>
      <th width="8%">备考</th>
      <th width="10%">操作人员</th>
    </tr>
    <tr>
      <td align="center">2011/1/1</td>
      <td align="center">  入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
	<tr>
      <td align="center">2011/1/1</td>
      <td align="center">  入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
	<tr>
      <td align="center">2011/1/1</td>
      <td align="center">  入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
	<tr>
      <td align="center">2011/1/1</td>
      <td align="center">  入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
	<tr>
      <td align="center">2011/1/1</td>
      <td align="center">  入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
	<tr>
      <td align="center">2011/1/1</td>
      <td align="center">入 </td>
      <td align="center">100</td>
      <td align="center">20</td>
      <td align="center">案件竞价</td>
      <td align="center">案件ID</td>
      <td align="center">管理员</td>
    </tr>
  </table>
  <div class="btn_os">
<div class="page"><span class="page_num">总共 880条记录   2/20</span><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
</div>