<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<style type="text/css">
	table tr {height: 32px;}
</style>


<div id="wraper">
	<!-- 法人信息查看 -->
	<h3 class="t_top"><? echo $this->tr('LP') . $this->tr('INFO') . $this->tr('VIEW')?></h3>
	<div id="tip_lpBaseinfo" class="tip"></div>
	<div class="marB">
		<form id="form_lpBaseinfo">
			<table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e5e5e5" class="tab_edit_case">
		      <tr>
		        <td width="41%" align="right" bgcolor="#FFFFFF"><span class="fred">*</span><?=$this->tr('COM_NAME')?>：</td>
		        <td width="59%" bgcolor="#FFFFFF" class="fblue">
		        	<input id="fullname" name="fullname" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_fullname" class="tip"></span>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('ADDR')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<input id="lp_address" name="lp_address" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_lp_address" class="tip"></span>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('WEBSITE')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<input id="website" name="website" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_website" class="tip"></span>
		        </td>
		      </tr><tr>
		      	<td align="right" bgcolor="#FFFFFF"><span class="fred">*</span><?=$this->tr('CONTACT')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<input id="lp_linkman" name="lp_linkman" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_lp_linkman" class="tip"></span>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><span class="fred">*</span><?=$this->tr('TEL')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<input id="tel" name="tel" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_tel" class="tip"></span>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><span class="fred">*</span><?=$this->tr('EMAIL')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<input id="email" name="email" type="text" value="" class="myinput" size="30" />
		        	<span id="tip_email" class="tip"></span>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('REG_TIME')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<?=$this->lp['create_time'];?>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('HIGH_LIGHT_DISPLAY_DEADLINE')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<?=$this->lp['highlightdate'];?>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('APPLY_VIEW_DEADLINE')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<?=$this->lp['applydate'];?>
		        </td>
		      </tr><tr>
		        <td align="right" bgcolor="#FFFFFF"><?=$this->tr('BALANCE')?>：</td>
		        <td bgcolor="#FFFFFF" class="fblue">
		        	<?=$this->lp['balance'];?>
		        </td>
		      </tr><tr>
		          <td colspan="2" style="text-align: center;">
		          	<a href="javascript: void(0);" id="btn_save" class="ENABLED_N">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_ok.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_admit" class="ENABLED_N">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_admint.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_stop" class="ENABLED_N">
			          	<img src="/img/admin/<?=$auth->locale?>/btn_stop.gif" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_viewEmps">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_look_user.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_viewCases">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_look_case.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_deposit">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_rujin.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_consumeDetail">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_look_history.jpg" class="marR" />
		          	</a>
		          	<a href="javascript: void(0);" id="btn_delete">
			          	<img src="/img/default/front/<?=$auth->locale?>/btn_del01.jpg" class="marR" />
		          	</a>
		          </td>
				</tr>
		    </table>
		    <!-- 隐藏信息 -->
		    <input id="code" name="code" type="hidden" value="" />
		</form>
	</div>
	
	
	<!-- 入金历史 -->
	<h3 class="t_top"><? echo $this->tr('DEPOSIT_AKB') . $this->tr('HISTORY')?></h3>
	<div class="search_result_lie01" id="depositAkbList"></div>
	
	
</div> <!-- <div id="wraper"> -->


<!-- 动态表，用于post方式提交请求，以免get方式时，用户获取到不该获取的请求方式信息 -->
<form id="form_dyn" action="" method="post" target="_blank">
	<input id="lpCode" name="lpCode" type="hidden" value="<?=$this->lp['code']?>" />
</form>


<!-- 创建入金：即购买点数按钮 -->
<div id="dlg_createDepositAkb" title="<?=$this->tr('CREATE_DEPOSIT_AKB')?>" style="display:none;">
	<div class="tip" id="tip_createDepositAkb"></div>
	<form id="form_createDepositAkb" method="post" action="">
    	<table id="table_createDepositAkb" width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_rujin">
			<tr>
				<td align="right"><?=$this->tr('DEPOSIT_AMT')?>：</td>
				<td align="left"><input type="text" name="c_amt" class="myinput" value="" /></td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('PURPOSE')?>：</td>
				<td align="left">
					<select name="c_svc" class="myselect">
						<option value=""><?=$this->tr('PLEASE_SELECT')?></option>
					<?php foreach ($this->svcs as $svc):?>
						<option value="<?=$svc?>"><?=$this->tr($svc)?></option>
					<?php endforeach;?>
					</select>
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('SERVICE_TAKE_EFFECT_DATE')?>：</td>
				<td align="left">
					<input id="dateBegin" name="dateBegin" type="text" value="" />
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('SERVICE_DEADLINE')?>：</td>
				<td align="left">
					<input id="dateEnd" name="dateEnd" type="text" value="" />
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('BUY_POINTS')?>：</td>
				<td align="left">
					<input type="text" name="c_points" class="myinput" value="" />
				</td>
			</tr>
		</table>
		<!-- 隐藏信息 -->
		<input id="c_usrCode" name="c_usrCode" type="hidden" value="<?=$this->lp['code']?>" />
	</form>
</div>


<script type="text/javascript">
	var lp = <?=json_encode($this->lp)?>;
	var DATE = '<?=$this->tr('DATE')?>';
	var DEPOSIT_AMT = '<?=$this->tr('DEPOSIT_AMT')?>';
	var PURPOSE = '<?=$this->tr('PURPOSE')?>';
	var SERVICE_TAKE_EFFECT_DATE = '<?=$this->tr('SERVICE_TAKE_EFFECT_DATE')?>';
	var SERVICE_DEADLINE = '<?=$this->tr('SERVICE_DEADLINE')?>';
	var BUY_POINTS = '<?=$this->tr('BUY_POINTS')?>';

	var NO_CHANGE = '<? echo $this->tr('NO_CHANGE')?>';
	var ALREADY_ADMIT = '<? echo $this->tr('ALREADY') . $this->tr('ADMIT')?>';
	var ALREADY_STOP = '<? echo $this->tr('ALREADY') . $this->tr('STOP')?>';
</script>
<script src="/js/admin/admin/lp/baseinfo.js" type="text/javascript"></script>