<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<style type="text/css">
	table {background-color: #f7f7ff; width: 100%; border: 0; cellpadding: 0; cellspacing: 1px;}
	table tr th {border: 0; text-align: right; width: 22%; padding-left:10px; padding-right:10px; line-height:30px;}
	table tr td {border: 0; text-align: left; width: 78%; padding-left:10px; padding-right:10px; line-height:30px;}
	.myinput {width:150px; height:20px; line-height:20px;}
</style>

<div id="wraper">
	<form id="form_adminInfo" name="form_adminInfo" method="post" action="">
		<div id="tip_adminInfo" class="tip"></div>
		<h3 class="msg_title"><?echo $this->tr('ADMIN'), $this->tr('SETTING')?></h3>
		<table>
	      <tr>
	        <th><?=$this->tr('COM_NAME')?>：</th>
	        <td>
				<input type="text" id="fullname" name="fullname" class="myinput" size="10" value="<?=$this->usr['fullname']?>" />
			 </td>
	      </tr>
	      <tr>
	        <th><?=$this->tr('TEL')?>：</th>
	        <td><input type="text" id="tel" name="tel" class="myinput" value="<?=$this->usr['tel']?>" /></td>
	      </tr>
	      <tr>
	        <th><?=$this->tr('email')?>：</th>
	        <td>
				<input type="text" id="email" name="email" class="myinput" value="<?=$this->usr['email']?>" />
			</td>
	      </tr>
	      <tr><td colspan="2" class="fblue" bgcolor="#f7f7ff"><?=$this->tr("IF_NEED_TO_MODIFY_PASSWD__PLEASE_INPUT_NEW_PASSWD__OR_LEAVE_IT")?></td></tr>
	      <tr>
	        <th valign="top"><?=$this->tr('PASSWORD')?>：</th>
	        <td>
				<input type="password" id="passwd" name="passwd" class="myinput" /><br />
					<?=$this->tr('PLEASE_CONFIRM_ONCE_AGAIN')?><br />
				<input type="password" id="passwd2" name="passwd2" class="myinput" />
			</td>
	      </tr>
	    </table>
		<div class="btn_center">
			<a href="javascript: saveAdminInfo();">
				<img alt="submit" src="/img/default/front/<?=$auth->locale?>/btn_ok.jpg" />
			</a>
		</div>
	</form>
</div>


<script type="text/javascript">
	var usr = <?=json_encode($this->usr)?>;
</script>
<script type="text/javascript" src="/js/admin/admin/admin/adminset.js"></script>