<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
  <form id="form1" name="form1" method="post" action="">
 <h3 class="title_bg">退会手续</h3>
 <div class="user_border">
 	<p class="user_unsubscrible_info">是否真的要退退会</p>
	<p class="btn_center">
		<a href="" target="_blank">
			<img src="/img/default/usr/<?=$auth->locale?>/btn_out.jpg" width="80" height="30" class="btn_marR" />
		</a>
		<a href="/usr_usr/usr" target="_blank">
			<img src="/img/default/front/<?=$auth->locale?>/btn_back.jpg" width="80" height="30" />
		</a>
	</p>
 </div>

  </form>
</div>