<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<div id="content">
	<div><?=$this->tip?></div>
	<div><?=$this->tr('REDIRECT_TO_HOMEPAGE_AFTER_THREE_SEC')?></div>
</div>

<script src="/js/jquery/jquery-1.7.2.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(function() {
		setTimeout("location.href = '/?pwd=10'", 3000);
	});

}); //End: $(document).ready
</script>



