<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<style type="text/css">
	#table_createDepositAkb tr {height: 24px;}
</style>


<div id="wraper">
	<h3 class="msg_title_bg"><?=$this->tr('DEPOSIT_AKB_QUERY')?></h3>
	<form id="form_depositAkb" method="post" action="">
		<div class="top_search_nobg">
			<ul>
				<li class="w01"><?=$this->tr('USERNAME')?>：</li>
				<li class="w02"><input type="text" name="fullname" class="myinput" /></li>
				<li class="w01"><?=$this->tr('SECTION')?>：</li>
				<li class="w02"><input type="text" name="minAmt" class="myinput" /></li>
				<li> ～</li>
				<li class="w02"><input type="text" name="maxAmt" class="myinput" /></li>
				<li class="w01"><?=$this->tr('SERVICE')?>：</li>
				<li class="w02">
					<select name="svc" class="myselect">
						<option value=""><?=$this->tr('ALL')?></option>
					<?php foreach ($this->svcs as $svc):?>
						<option value="<?=$svc?>"><?=$this->tr($svc)?></option>
					<?php endforeach;?>
					</select>
				</li>
				<li>
					<a href="javascript:void(0);" id="btn_searchAkb">
						<img alt="Search" src="/img/default/front/<?=$auth->locale?>/btn_cx.gif" />
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" id="btn_createDepositAkb">
						<img src="/img/default/front/<?=$auth->locale?>/btn_rujin.jpg" width="84" height="26" />
					</a>
				</li>
			</ul>
		</div>
	</form>
	<div class="search_result_lie01" id="depositAkbList"></div>
</div> <!-- <div id="wraper"> -->


<!-- 创建入金：即购买点数按钮 -->
<div id="dlg_createDepositAkb" title="<?=$this->tr('CREATE_DEPOSIT_AKB')?>" style="display:none;">
	<div class="tip" id="tip_createDepositAkb"></div>
	<form id="form_createDepositAkb" method="post" action="">
    	<table id="table_createDepositAkb" width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_rujin">
			<tr>
				<td align="right">
<!--					<button id="btn_mbr" type="button"><?=$this->tr('INVIDIDUAL')?></button>-->
					<button id="btn_lp" type="button"><?=$this->tr('LP')?></button>
				</td>
				<td align="left">
					<input id="c_fullname" readonly="readonly" type="text" value="" />
					<span id="c_roleName"></span>
					<input id="c_usrCode" name="c_usrCode" type="hidden" value="" />
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('DEPOSIT_AMT')?>：</td>
				<td align="left"><input type="text" name="c_amt" class="myinput" value="" /></td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('PURPOSE')?>：</td>
				<td align="left">
					<select name="c_svc" class="myselect">
						<option value=""><?=$this->tr('PLEASE_SELECT')?></option>
					<?php foreach ($this->svcs as $svc):?>
						<option value="<?=$svc?>"><?=$this->tr($svc)?></option>
					<?php endforeach;?>
					</select>
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('SERVICE_TAKE_EFFECT_DATE')?>：</td>
				<td align="left">
					<input id="dateBegin" name="dateBegin" type="text" value="" />
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('SERVICE_DEADLINE')?>：</td>
				<td align="left">
					<input id="dateEnd" name="dateEnd" type="text" value="" />
				</td>
			</tr>
			<tr>
				<td align="right"><?=$this->tr('BUY_POINTS')?>：</td>
				<td align="left">
					<input type="text" name="c_points" class="myinput" value="" />
				</td>
			</tr>
		</table>
	</form>
</div>


<!-- dlg：选择个人，同时设置usr_code -->
<div id="dlg_mbrList" title="<?=$this->tr('INVIDIDUAL')?>" style="display: none;">
	<div id="tip_mbrList" class="tip"></div>
	<div>
		<?=$this->tr('NAME')?>：
		<input id="s_fullname" type="text" value="" />
		<button id="btn_searchMbr" type="button"><?=$this->tr('SEARCH')?></button>
	</div>
	<div id="mbrList"></div>
</div>


<!-- dlg：选择法人，同时设置usr_code -->
<div id="dlg_lpList" title="<?=$this->tr('LP')?>" style="display: none;">
	<div id="tip_lpList" class="tip"></div>
	<div>
		<?=$this->tr('LP_NAME')?>：
		<input id="s_lpName" type="text" value="" />
		<button id="btn_searchLp" type="button"><?=$this->tr('SEARCH')?></button>
	</div>
	<div id="lpList"></div>
</div>


<script type="text/javascript">
	var USR_ID = '<?=$this->tr('USR_ID')?>';
	var USERNAME = '<?=$this->tr('USERNAME')?>';
	var DATE = '<?=$this->tr('DATE')?>';
	var DEPOSIT_AMT = '<?=$this->tr('DEPOSIT_AMT')?>';
	var PURPOSE = '<?=$this->tr('PURPOSE')?>';
	var SERVICE_TAKE_EFFECT_DATE = '<?=$this->tr('SERVICE_TAKE_EFFECT_DATE')?>';
	var SERVICE_DEADLINE = '<?=$this->tr('SERVICE_DEADLINE')?>';
	var BUY_POINTS = '<?=$this->tr('BUY_POINTS')?>';

	//本地化个人、法人或管理员信息：用于管理员代替个人、法人（为其员工）或为自己的员工创建简历时，选择个人、法人或管理员
	var INVIDIDUAL = '<?=$this->tr('INVIDIDUAL')?>';
	var LP = '<?=$this->tr('LP')?>';
	
	var MEMBER_CODE = '<?=$this->tr('MEMBER_CODE')?>';
	var EMAIL = '<?=$this->tr('email')?>';
	var FULLNAME = '<?=$this->tr('FULLNAME')?>';

	var LP_CODE = '<?=$this->tr('LP_CODE')?>';
	var LP_NAME = '<?=$this->tr('LP_NAME')?>';
</script>
<script src="/js/admin/akb/depositakb.js" type="text/javascript"></script>