<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
	<div class="ad_left">
	<h3 class="ad_t01">广告分类</h3>
	<div class="ad_sort">
	<ul>
	<li><a href="/front_ad/adlist" target="_blank">FX</a></li>
	<li><a href="/front_ad/adlist" target="_blank">信用卡</a></li>
	</ul>
	</div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div style="height:160px; background-color:#e9e9e9;"></div>
	</div>
	<div class="ad_center">
	<h3 class="tbg_01">FX返金集合</h3>
	<div class="ad_con">
	<ul>
	<li>
		<img src="/img/default/front/<?=$auth->locale?>/ad02.jpg" width="100" height="96" class="fl" />
		<div class="ad_detail">
			<h3><a href="/front_ad/addetail" target="_blank">GMO公司  期间返金</a></h3>
			<div class="marB">活动期间：2012/03/25  ～  2012/04/25</div>
			<div><a href="#" target="_blank">
					<img src="/img/default/front/<?=$auth->locale?>/btn_gain.jpg" width="61" height="23" border="0" align="middle" class="btn_marR" />
				</a>口座開設完了
			</div>
		</div>
		<div class="btn_link">返金额:10000円<br />
		  <a href="/front_ad/addetail" target="_target">
		  	<img src="/img/default/front/<?=$auth->locale?>/btn_detail.jpg" width="106" height="24" border="0" />
		  </a>
		</div>
	</li>
	</ul>
	</div>
	<h3 class="tbg_01">信用卡返金集合</h3>
	<div class="ad_con">
	<ul>
	<li>
	<img src="/img/default/front/<?=$auth->locale?>/ad02.jpg" width="100" height="96" class="fl" />
	<div class="ad_detail">
	<h3><a href="/front_ad/addetail" target="_blank">GMO公司  期间返金</a></h3>
	<div class="marB">活动期间：2012/03/25  ～  2012/04/25</div>
	<div><img src="/img/default/front/<?=$auth->locale?>/btn_gain.jpg" width="61" height="23" align="middle" class="btn_marR" />口座開設完了</div>
	</div>
	<div class="btn_link">返金额:10000円<br />
		<a href="/front_ad/addetail" target="_target">
			<img src="/img/default/front/<?=$auth->locale?>/btn_detail.jpg" width="106" height="24" />
		</a>
	</div>
	</li>
	</ul>
	</div>
	</div>
	<div class="ad_right">
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div style="height:160px; background-color:#e9e9e9;"></div>
	</div>
	<br class="cls" />	
</div>


