<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.STYLE1 {
	color: #0000FF;
	font-weight: bold;
}
.STYLE2 {color: #006600}
.STYLE3 {color: #009900}
-->
</style>

<div id="wraper">
	<div class="ad_left">
	<h3 class="ad_t01">广告分类</h3>
	<div class="ad_sort">
	<ul>
	<li><a href="#" target="_self">FX</a></li>
	<li><a href="#" target="_blank">信用卡</a></li>
	</ul>
	</div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div style="height:200px; background-color:#e9e9e9;"></div>
	</div>
	<div class="ad_center">
	<h3 class="tbg_01">FX返金集合</h3>
	<div class="ad_con">
	<ul>
	<li>
	<img src="/img/default/front/<?=$auth->locale?>/ad02.jpg" width="100" height="96" class="fl" />
	<div class="ad_detail">
	<h3><a href="#" target="_self">GMO公司  期间返金</a></h3>
	<div class="marB">活动期间：2012/03/25  ～  2012/04/25</div>
	<div><a href="#" target="_self"><img src="/img/default/front/<?=$auth->locale?>/btn_gain.jpg" width="61" height="23" border="0" align="absmiddle" class="btn_marR" /></a>口座開設完了</div>
	</div>
	<div class="btn_link">返金额:10000円<br />
	  <a href="#" target="_self"><img src="/img/default/front/<?=$auth->locale?>/btn_detail.jpg" width="106" height="24" border="0" /></a></div>
	</li>

	</ul>
	<h3 class="tbg_grey01">详细说明</h3>
	<div class="f14 conU"><em>本贴最后由blusesky4m于12-1-11 23：02 编辑</em></div>
	<div class="ad_detail_con">
	<p class="f12">＝＝＝＝＝＝＝<span class="STYLE3">（Chinese Wa Badminton Club Since 2007）</span>＝＝＝＝＝＝＝＝＝＝＝＝  	  </p>
	  	<p class="f14"><span class="STYLE1">【本次活动发起组群】</span>：中国娃羽毛球俱乐部（CWBC）</p>
	  	<p class="f14"><span class="STYLE1">【俱乐部日文HP】</span>：http://sports.geocities.js/cwbc_2007 </p>
	  	<p class="f12">＝＝＝＝＝＝＝<span class="STYLE2">（Chinese Wa Badminton Club Since 2007）</span>＝＝＝＝＝＝＝＝＝＝＝＝ </p>
	  	<p class="fred f14"><strong>本次活动是开自家车前往神州大地<br />
	  	  住箱根，打羽毛球，泡温泉。等等<br />
  	    由于定员有限，优先中国娃俱全的成员报名参加</strong></p>
	</div>
	<h3 class="tbg_grey01">留言</h3>
	<div class="leave_word"></div>	
	<ul class="ad_comment">
		<li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg" width="48" height="48" class="photo" />
		<div class="detail">
			<p><span class="fr"><a href="#" target="_self">回复</a></span><span class="fblue"><strong>bluesky4m</strong></span> <span class="fgrey">2012-2-3 23:59</span></p>
		    <p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>
			<p>8/16</p>
			<p>张三带一人，李四带二人。</p>
		</div>
		<br class="cls" /> 
		  </li>
		 <li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg" width="48" height="48" class="photo" />
		<div class="detail">
			<p><span class="fr"><a href="#" target="_self">回复</a></span><span class="fblue"><strong>bluesky4m</strong></span> <span class="fgrey">2012-2-3 23:59</span></p>
		    <p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>
			<p>8/16</p>
			<p>张三带一人，李四带二人。</p>
		</div>
		<br class="cls" /> 
		  </li>
		 <li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg" width="48" height="48" class="photo" />
		<div class="detail">
			<p><span class="fr"><a href="#" target="_self">回复</a></span><span class="fblue"><strong>bluesky4m</strong></span> <span class="fgrey">2012-2-3 23:59</span></p>
		    <p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>
			<p>8/16</p>
			<p>张三带一人，李四带二人。</p>
		</div>
		<br class="cls" /> 
		  </li>
		  
		 <li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg" width="48" height="48" class="photo" />
		<div class="detail">
			<p><span class="fr"><a href="#" target="_self">回复</a></span><span class="fblue"><strong>bluesky4m</strong></span> <span class="fgrey">2012-2-3 23:59</span></p>
		    <p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>
			<p>8/16</p>
			<p>张三带一人，李四带二人。</p>
		</div>
		<br class="cls" /> 
		  </li> 
		  <li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg" width="48" height="48" class="photo" />
		<div class="detail">
			<p><span class="fr"><a href="#" target="_self">回复</a></span><span class="fblue"><strong>bluesky4m</strong></span> <span class="fgrey">2012-2-3 23:59</span></p>
		    <p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>
			<p>8/16</p>
			<p>张三带一人，李四带二人。</p>
		</div>
		<br class="cls" /> 
		  </li>
		 
		</ul>
		<div class="btn_os">
  <div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
	</div>
	</div>
	<div class="ad_right">
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div style="height:200px; background-color:#e9e9e9;"></div>
	</div>
	<br class="cls" />	
</div>