<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
	<div id="left">
		<!--search detail-->		
		<div class="c_case_search">
	<form id="form2" name="form2" method="post" action="">
		<h4 class="case_search_title">人员种类</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><label>
                <input type="radio" name="radiobutton" value="radiobutton" />
              </label>
              所有人员</td>
              <td><label>
                <input type="radio" name="radiobutton" value="radiobutton" />
              新增人员</label></td>
              <td><label>
                <input type="radio" name="radiobutton" value="radiobutton" />
              </label>
              推荐人员</td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title">选择OS</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="33%">
                <label>
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                </label>
                Windows</td>
              <td width="35%"><label>
                <input type="checkbox" name="checkbox8" value="checkbox" />
                linux,Unix</label></td>
              <td width="32%"><label>
                <input type="checkbox" name="checkbox24" value="checkbox" />
              </label>
              Android </td>
            </tr>
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox3" value="checkbox" />
                Iphone</label></td>
              <td><label>
                <input type="checkbox" name="checkbox9" value="checkbox" />
                              OS390</label></td>
              <td><label>
                <input type="checkbox" name="checkbox25" value="checkbox" />
              </label>
              其它</td>
            </tr>
          </table>
		</div>		
		<div class="fl w03">
		<h4 class="case_search_title">选择经验语言/FrameWork（N年以上）</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="28%">
                <label>
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                </label>
                JAVA</td>
              <td width="15%" align="left" valign="middle"><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td width="39%"><label>
                <input type="checkbox" name="checkbox8" value="checkbox" />
                C/C++/VC++</label></td>
              <td width="18%"><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label><input type="checkbox" name="checkbox3" value="checkbox" /></label> COBOL</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label><input type="checkbox" name="checkbox9" value="checkbox" /> .NET（c#/VB/ASP）</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label><input type="checkbox" name="checkbox4" value="checkbox" /></label> PHP</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label><input type="checkbox" name="checkbox10" value="checkbox" /></label> SAP/ABAP</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>

              <td><label><input type="checkbox" name="checkbox5" value="checkbox" /></label> Struts</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label><input type="checkbox" name="checkbox11" value="checkbox" /></label> EJB</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label><input type="checkbox" name="checkbox26" value="checkbox" /></label> Intra-mart</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label><input type="checkbox" name="checkbox27" value="checkbox" /></label> Terasoruna</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label><input type="checkbox" name="checkbox7" value="checkbox" /></label> 其他</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table>
		</div>
		</div>
		<div class="fr w04">
		<h4 class="case_search_title">选择业务领域（N年以上）</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="26%">
                <label>
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                </label>
                证券</td>
              <td width="24%"><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td width="25%"><label>
                <input type="checkbox" name="checkbox8" value="checkbox" />
                银行</label></td>
              <td width="25%"><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox3" value="checkbox" />
                保险</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label>
                <input type="checkbox" name="checkbox9" value="checkbox" />
                流通</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox4" value="checkbox" />
                人事</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label>
                <input type="checkbox" name="checkbox10" value="checkbox" />
                经理</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox5" value="checkbox" />
                携带</label></td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
              <td><label>
                <input type="checkbox" name="checkbox11" value="checkbox" /></label>
                其它</td>
              <td><label>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </label></td>
            </tr>
          </table>
		</div>
		</div>
		<br class="cls" />
		<h4 class="case_search_title">选择勤务地</h4>
		<div class="address_t">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><label><input type="checkbox" name="checkbox13" value="checkbox" /></label>		日本 </td>
            </tr>
          </table>
		</div>
		<div class="address_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox14" value="checkbox" />
                北海道</label></td>
              <td><label>
                <input type="checkbox" name="checkbox15" value="checkbox" />
                东北</label></td>
              <td><label>
                <input type="checkbox" name="checkbox16" value="checkbox" />
                关东              </label></td>
              <td><label>
                <input type="checkbox" name="checkbox17" value="checkbox" />
                东海</label></td>
              <td><label>
                <input type="checkbox" name="checkbox18" value="checkbox" />
                北信越</label></td>
            </tr>
            <tr>
              <td><label>
                <input type="checkbox" name="checkbox19" value="checkbox" />
                关西</label></td>
              <td><label>
                <input type="checkbox" name="checkbox20" value="checkbox" />
                中国.四国</label></td>
              <td><label>
                <input type="checkbox" name="checkbox21" value="checkbox" />
                九州.冲绳</label></td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table>
		</div>
		<div class="address_t">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><label><input type="checkbox" name="checkbox13" value="checkbox" /></label>		海外 </td>
            </tr>
          </table>
		</div>
		<div class="address_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="19%"><label>
                <input type="checkbox" name="checkbox22" value="checkbox" />
                 中国</label></td>
              <td width="23%"><label>
                <input type="checkbox" name="checkbox23" value="checkbox" />
                其他</label></td>
              <td width="22%">&nbsp;</td>
              <td width="16%">&nbsp;</td>
              <td width="20%">&nbsp;</td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title"><label><input type="checkbox" name="checkbox2" value="checkbox" /></label> 其他条件</h4>
		<div class="else_item">
		  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr>
              <td width="8%">性  别</td>
              <td width="23%"><label>
                <select name="select" class="myselect01">
                  <option>全部</option>
                  <option>男</option>
                  <option>女</option>
                </select>
              </label></td>
              <td width="9%" align="center">年龄 </td>
              <td width="60%"><label>
                <select name="select" class="select_year">
                </select>
              </label>～<label>
                <select name="select" class="select_year">
                </select>
              </label></td>
            </tr>
          </table>
		</div>
		<div class="else_item">
		  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr>
              <td width="26%"><label>
                <select name="select" class="myselect01">
                  <option>所有</option>
                </select>
              </label></td>
              <td width="14%"><label>
                <input type="radio" name="radiobutton" value="radiobutton" />
              即日</label></td>
              <td width="60%"><label>
                <input type="radio" name="radiobutton" value="radiobutton" />
              </label><input class="Wdate" type="text" onClick="WdatePicker()">～<input class="Wdate" type="text" onClick="WdatePicker()"></td>
            </tr>
          </table>
		</div>
		<div class="else_item"><label><span class="fblue"><strong>单价</strong></span>
	    <input type="text" name="textfield2" class="search_input_time" /></label>以上
	   </div>
		<div class="btn_search">
		  <label>
		  <input alt="Search" type="image" id="btn_search" src="/img/default/front/<?=$auth->locale?>/btn_search.jpg" />
		  </label>
		</div>
	</form>
	</div>
	</div>
	<div id="right">
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
	<div class="marB" style="height:160px; background-color:#e9e9e9;"></div>
	<div style="height:100px; background-color:#e9e9e9;"></div>
	</div>
<br class="cls" />
</div>
<script src="/js/default/front/talent/talentsearch.js" type="text/javascript"></script>