<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
	<!-- 左右：高级人才检索 -->
	<div id="left">
		<!--search detail-->		
		<div class="c_case_search">
			<form id="form_advancedSearch" name="form_advancedSearch" method="post" action="/front_talent/talentsearchresult" target="_blank">
				<!-- 选择：人员种类 -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('PEOPLE_KIND')?></h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <tr>
			              <td><input type="radio" name="talentType" value="ALL" checked="checked" />
			             	<?=$this->tr('ALL_PEOPLE')?>(<span style="color: red;"><?=$this->allTalentsCnt?></span>)
			              </td>
			              <td><input type="radio" name="talentType" value="NEW" />
			                <?=$this->tr('NEW_PEOPLE')?>(<span style="color: red;"><?=$this->newTalentsCnt?></span>)
			              </td>
			              <td><input type="radio" name="talentType" value="RECMD" />
			                <?=$this->tr('RECMD_PEOPLE')?>(<span style="color: red;"><?=$this->recmdTalentsCnt?></span>)
			              </td>
			            </tr>
			          </table>
					</div>
				</div>
				
				<!-- 选择OS -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('CHOOSE')?>OS</h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <tr>
			            <?php for ($i = 0; $i < count($this->oss); $i++) {
			            	if ($i % 5 == 0) {
			            		echo "</tr><tr><td><input type='checkbox' name='oss[]' value='{$this->oss[$i]}' />{$this->tr($this->oss[$i])}</td>";	
			            	} else {
			            		echo "<td><input type='checkbox' name='oss[]' value='{$this->oss[$i]}' />{$this->tr($this->oss[$i])}</td>";
			            	}
			            }?>
			            </tr>
			          </table>
					</div>
				</div>
			
				<!-- 选择经验语言/FrameWork(N年以上)-->
				<div class="fl w01">
					<h4 class="case_search_title"><?=$this->tr('CHOOSE')?><?=$this->tr('EXPERIENCE_LANGUAGE')?>/FrameWork(N<?=$this->tr('YEAR')?><?=$this->tr('ABOVE')?>)</h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search tab_bg">
			            <tr>
			            <?php for ($i = 0; $i < count($this->fws); $i++):?>
			            	<?php if ($i % 3 == 0):?>
			            		</tr><tr><td><?=$this->tr($this->fws[$i])?></td>
			            		<td>
			            			<select id="<?=$this->fws[$i]?>_fw_age" name="<?=$this->fws[$i]?>_fw_age" class="select_w38">
				            			<?php foreach ($this->experienceYears as $experienceYear):?>
				            				<option value="<?=$experienceYear?>"><?=$experienceYear?></option>
										<?php endforeach;?>
									</select>
			            		</td>
			            	<?php else:?>
			            		<td><?=$this->tr($this->fws[$i])?></td>
			            		<td>
			            			<select id="<?=$this->fws[$i]?>_fw_age" name="<?=$this->fws[$i]?>_fw_age" class="select_w38">
				            			<?php foreach ($this->experienceYears as $experienceYear):?>
				            				<option value="<?=$experienceYear?>"><?=$experienceYear?></option>
										<?php endforeach;?>
									</select>
				          		</td>
			            	<?php endif;?>
			            <?php endfor;?>
			            </tr>
			          </table>
					</div>
				</div>
				  
				<!-- 选择业务领域(N年以上)  -->
				<div class="fr w02">
					<h4 class="case_search_title"><?=$this->tr('CHOOSE')?><?=$this->tr('BIZ_FIELD')?>(N<?=$this->tr('YEAR')?><?=$this->tr('ABOVE')?>)</h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search tab_bg">
			            <tr>
			            <?php for ($i = 0; $i < count($this->bizs); $i++):?>
			            	<?php if ($i % 2 == 0):?>
			            		</tr><tr><td><?=$this->tr($this->bizs[$i])?></td>
			            		<td>
			            			<select id="<?=$this->bizs[$i]?>_biz_age" name="<?=$this->bizs[$i]?>_biz_age" class="select_w38">
				            			<?php foreach ($this->experienceYears as $experienceYear):?>
				            				<option value="<?=$experienceYear?>"><?=$experienceYear?></option>
										<?php endforeach;?>
									</select>
			            		</td>
			            	<?php else:?>
			            		<td><?=$this->tr($this->bizs[$i])?></td>
			            		<td>
			            			<select id="<?=$this->bizs[$i]?>_biz_age" name="<?=$this->bizs[$i]?>_biz_age" class="select_w38">
				            			<?php foreach ($this->experienceYears as $experienceYear):?>
				            				<option value="<?=$experienceYear?>"><?=$experienceYear?></option>
										<?php endforeach;?>
									</select>
				          		</td>
			            	<?php endif;?>
			            <?php endfor;?>
			            </tr>
			          </table>
					</div>
				</div>
				<br class="cls" />
					
				<!-- 选择勤务地 -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('CHOOSE')?><?=$this->tr('WORKPLACE')?></h4>
					<div class="address_t">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <tr>
			              <td><input type="checkbox" id="expWps_jp_all" value="" /><?=$this->tr('Japan')?></td>
			            </tr>
			          </table>
					</div>
					<div class="address_con">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <?php for ($i = 0; $i < count($this->expWps_jp); $i++) {
			            	if ($i % 5 == 0) {
			            		echo "</tr><tr><td><input type='checkbox' name='expWps_jp[]' value='{$this->expWps_jp[$i]}' />{$this->tr($this->expWps_jp[$i])}</td>";	
			            	} else {
			            		echo "<td><input type='checkbox' name='expWps_jp[]' value='{$this->expWps_jp[$i]}' />{$this->tr($this->expWps_jp[$i])}</td>";
			            	}
		            	}?>
			          </table>
					</div>
					<div class="address_t">
					  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <tr>
			              <td><input type="checkbox" id="expWps_os_all" value="" /><?=$this->tr('OVERSEA')?></td>
			            </tr>
			          </table>
					</div>
					<div class="address_con">
					  <table width="45%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			            <?php for ($i = 0; $i < count($this->expWps_os); $i++) {
			            	if ($i % 5 == 0) {
			            		echo "</tr><tr><td><input type='checkbox' name='expWps_os[]' value='{$this->expWps_os[$i]}' />{$this->tr($this->expWps_os[$i])}</td>";	
			            	} else {
			            		echo "<td><input type='checkbox' name='expWps_os[]' value='{$this->expWps_os[$i]}' />{$this->tr($this->expWps_os[$i])}</td>";
			            	}
		            	}?>
			          </table>
					</div>
				</div>
				
				<!-- 其他条件  -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('OTHER_COND')?></h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
			            <tr>
			              <td width="6%"><?=$this->tr('SEX__')?></td>
			              <td width="36%">
			                <input type="radio" name="sex" value="" checked="checked" /><?=$this->tr('WHOLE')?>
			                &nbsp;&nbsp;
			                <input type="radio" name="sex" value="M" /><?=$this->tr('M')?>
			                &nbsp;&nbsp;
							<input type="radio" name="sex" value="F" /><?=$this->tr('F')?>
						  </td>
			              <td width="4%"><?=$this->tr('AGE')?></td>
			              <td width="54%">
			                <select id="fullageMin" name="fullageMin" class="select_year">
			                	<option value=""><?=$this->tr('PLEASE_SELECT')?></option>
			                	<?php for ($i = 20; $i < 60; $i++):?>
			                	<option value="<?=$i?>"><?=$i?></option>
			                	<?php endfor;?>
			                </select>
							～
			                <select id="fullageMax" name="fullageMax" class="select_year">
			                	<option value=""><?=$this->tr('PLEASE_SELECT')?></option>
			                	<?php for ($i = 20; $i < 60; $i++):?>
			                	<option value="<?=$i?>"><?=$i?></option>
			                	<?php endfor;?>
			                </select>
			              </td>
			            </tr>
			            <tr>
			              <td><?=$this->tr('JAPANESE')?></td>
			              <td colspan="3">
							  <select id="jaAbility" name="jaAbility" class="myselect">
						    	<option value=""><?=$this->tr('PLEASE_SELECT')?></option>
							    <?php $jaLevels = array('A', 'B', 'C', 'D', 'E'); foreach ($jaLevels as $jaLevel):?>
							    	<option value="<?=$jaLevel?>"><?=$this->tr('JA_ABILITY_' . $jaLevel)?></option>
							    <?php endforeach;?>
						      </select>
					  	  </td>
			            </tr>
			          </table>
					</div>
				</div>
					
				<!-- 稼动可日期 -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('ABLE_WORK_DATE')?></h4>
					<div class="case_search_con">
					  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
			            <tr>
			              <td width="12%">
			                <input type="radio" name="ableWorkDateChoice" value="FROM_NOW_ON" /><?=$this->tr('FROM_NOW_ON')?>
			              </td>
			              <td width="88%">
			                <input type="radio" name="ableWorkDateChoice" value="SPECIFY_DATE" />
			              	<input id="ableWorkDateBegin" name="ableWorkDateBegin" type="text" value=""> 
			              	～
			              	<input id="ableWorkDateEnd" name="ableWorkDateEnd" type="text" value="">
			              </td>
			            </tr>
			          </table>
					</div>
				</div>
					
				<!-- 单价 -->
				<div>
					<h4 class="case_search_title"><?=$this->tr('UNIT_PRICE')?></h4>
					<div class="case_search_con">
						<input type="text" id="salaryMin" name="salaryMin" class="myinput" /><?=$this->tr('ABOVE')?>
					</div>
				</div>
				<!-- 按钮 -->
				<div class="btn_search"><a href="javascript:void(0);" id="btn_advancedSearch"><img src="/img/default/front/<?=$auth->locale?>/btn_search.jpg" width="191" height="38" border="0" /></a></div>
			</form>
		</div>
		
	</div>
	
	<!-- 右侧：广告 -->	
	<div id="right">
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div class="marB" style="height:200px; background-color:#e9e9e9;"></div>
		<div style="height:160px; background-color:#e9e9e9;"></div>
	</div>
<br class="cls" />
</div>

<script type="text/javascript">
	var jsAdvancedSearchParms = '<?=$this->jsAdvancedSearchParms?>';
	var advancedSearchParms;
	if (jsAdvancedSearchParms) {
		advancedSearchParms = JSON.parse(jsAdvancedSearchParms);
	}
	var fws = JSON.parse('<?=json_encode($this->fws)?>');
	var bizs = JSON.parse('<?=json_encode($this->bizs)?>');
</script>
<script src="/js/default/front/talent/talent.js" type="text/javascript"></script>