<?php $auth = new Zend_Session_Namespace('AUTH');?>
<link href="/css/default/index.css" rel="stylesheet" type="text/css" />
<style type="text/css">
	.share .floatL {POSITION: relative; WIDTH: 28px; height:86px;background:url(/img/default/front/<?=$auth->locale?>/share.jpg) no-repeat left top;}
</style>
<?php $auth = new Zend_Session_Namespace('AUTH');?>
<div id="wraper">
<div id="left">
	<div class="case_info">
		<?=$this->tr('cases_new')?>:<span class="fred"><?=$this->newCasesCnt . $this->tr('unit_piece')?></span> 
		<?=$this->tr('TOTAL_CASES_COUNT')?>:<span class="fred"><?=$this->totalCaseCnt . $this->tr('unit_piece')?></span> 
		<?=$this->tr('TOTAL_TALENT_COUNT')?>:
			<span class="fred"><?=$this->talentsCnt . $this->tr('unit_person')?></span>
			(<?=$this->tr('PUBLIC')?>:<span class="fred"><?=$this->pubTalentsCnt . $this->tr('unit_person')?></span>，
			<?=$this->tr('UNPUBLIC')?>:<span class="fred"><?=$this->unpubTalentsCnt . $this->tr('unit_person')?></span>
			)
	</div>
	
	<!--推荐案件-->
	<h3 class="t_left">
		<span class="more"> 
			<a href="/front_case/casesearchresult/casetype/cases_recommend" ><?=$this->tr('MORE')?>&gt;&gt;</a> 
		</span>
		<span class="title"><?=$this->tr('cases_recommend')?></span>
		（<?=$this->recommendCasesCnt.$this->tr('unit_piece')?>）
	</h3>
	<?if(!empty($this->recommendCases)): foreach ($this->recommendCases as $case):?>
	<div class="con_case">
		<ul>
			<li class="w01">
				<a href="#" target="_blank">
					<img src="/img/default/front/<?=$auth->locale?>/case_pic02.jpg" width="58" height="38" border="0" />
	<!--				<img src="/img/default/front/<?=$auth->locale?>/case_pic01.jpg" width="58" height="38" border="0" />-->
				</a>
			</li>
			<li class="w02">
				<h4><span class="price"><?=$this->tr('case_unit_price')?>：<?=$case['unitPriceValueView']?></span>
					<a href="/front_case/casedetail/caseCode/<?=$case['code']?>" target="_blank"><?=$case['name']?></a></h4>
				<p> <? if (!empty($case['technicalReqValue'])):?>
						<?=$this->tr('case_technical_req')?>：<?=$case['technicalReqValue']?>
					<?endif;?>，
					<?=$this->tr('case_end_range')?>：<?=$case['period']?>，
					<?=$this->tr('case_delay')?>：<?=$case['delayValue']?>，
					<?=$this->tr('WORKPLACE')?>：<?=$case['workingPlaceValue']?>
				</p>
			</li>
<!--			<li class="w03"><?=$this->tr('case_unit_price')?>：<?=$case['unitPriceValueView']?></li>-->
		</ul>
	</div>
	<?endforeach; endif;?>

	<!-- 新增案件 -->
	<h3 class="t_left">
		<span class="more">
			<a href="/front_case/casesearchresult/casetype/cases_new" ><?=$this->tr('MORE')?>&gt;&gt;</a>
		</span>
		<span class="title"><?=$this->tr('cases_new')?></span>
		（<?=$this->newCasesCnt.$this->tr('unit_piece')?>）
	</h3>
	<?if(isset($this->newCases) && !empty($this->newCases)):foreach ($this->newCases as $case):?>
		<div class="con_case">
			<ul>
				<li class="w01">
					<a href="#" target="_blank">
						<img src="/img/default/front/<?=$auth->locale?>/case_pic02.jpg" width="58" height="38" border="0" />
						<!-- <img src="/img/default/front/<?=$auth->locale?>/case_pic01.jpg" width="58" height="38" border="0" />-->
					</a>
				</li>
				<li class="w02">
					<h4><span class="price"><?=$this->tr('case_unit_price')?>：<?=$case['unitPriceValueView']?></span>
						<a href="/front_case/casedetail/caseCode/<?=$case['code']?>" target="_blank"><?=$case['name']?></a></h4>
					<p> <? if (!empty($case['technicalReqValue'])):?>
							<?=$this->tr('case_technical_req')?>：<?=$case['technicalReqValue']?>
						<?endif;?>，
						<?=$this->tr('case_end_range')?>：<?=$case['period']?>，
						<?=$this->tr('case_delay')?>：<?=$case['delayValue']?>，
						<?=$this->tr('WORKPLACE')?>：<?=$case['workingPlaceValue']?>
					</p>
				</li>
<!--				<li class="w03"><?=$this->tr('case_unit_price')?>：<?=$case['unitPriceValueView']?></li>-->
			</ul>
		</div>
	<?endforeach;endif;?>


	<!-- 推荐用户 -->
	<h3 class="t_left">
		<span class="more"> 
			<a href="/front_talent/talentsearchresult/talentType/RECMD" target="_target">
				<?=$this->tr('MORE')?>&gt;&gt;
			</a>
		</span> 
		<span class="title"><?=$this->tr('RECMD_USR')?></span>
		（<?=$this->recmdMbrsCnt?><?=$this->tr('unit_a')?>）
	</h3>
<?php if (!empty($this->recmdMbrs)): foreach($this->recmdMbrs as $recmdMbr):?>
	<div class="con_user">
		<ul>
			<li class="w01">
				<a href="/usr_resume/previewresume/resumeCode/<?=$recmdMbr['code']?>" target="_blank">
					<?=$recmdMbr['talent_code']?>
				</a>
			</li>
			<li class="w02">
				<?=$this->tr($recmdMbr ['sex'])?>
				<? echo $recmdMbr['age'], $this->tr('YEARS_OLD')?>&nbsp;
				<?=$recmdMbr['experience']?>&nbsp;
				<?=$recmdMbr['skill']?>
			</li>
			<li class="w03">
				<?=$this->tr('WORK_DATE')?>：<?=$recmdMbr['adjust_able_work_date']?>
			</li>
		</ul>
	</div>
<?php endforeach; endif;?>
	
	
	<!--新增用户-->
	<h3 class="t_left">
		<span class="more"> 
			<a href="/front_talent/talentsearchresult/talentType/NEW" target="_target">
				<?=$this->tr('MORE')?>&gt;&gt;
			</a>
		</span>
		<span class="title">
			<?=$this->tr('NEW_USR')?>
		</span>
		（<?=$this->newMbrsCnt?><?=$this->tr('unit_a')?>）
	</h3>
<?php if (!empty($this->newMbrs)): foreach ($this->newMbrs as $newMbr):?>
	<div class="con_user">
		<ul>
			<li class="w01">
				<a href="/usr_resume/previewresume/resumeCode/<?=$recmdMbr['code']?>" target="_blank">
					<?=$newMbr['talent_code']?>
				</a>
			</li>
			<li class="w02">
				<?=$this->tr ($newMbr['sex'])?>
				<? echo $newMbr['age'], $this->tr('YEARS_OLD')?>&nbsp;
				<?=$newMbr['experience']?>&nbsp;
				<?=$newMbr['skill']?>
			</li>
			<li class="w03">
				<?=$this->tr('WORK_DATE')?>:<?=$newMbr['adjust_able_work_date']?>
			</li>
		</ul>
	</div>
<?php endforeach; endif;?>
	
	
	<!-- 案件检索-->
	<form method="post" id="dynForm">
	<h3 class="t_case_search"><?=$this->tr('case_search')?></h3>
	<div class="c_case_search">
		<!-- 选择职种 -->
		<h4 class="case_search_title">  <input type="checkbox" name="careersAll"/> <?=$this->tr('please_choice_careers')?></h4>
		<div class="case_search_con">
		<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr>
			<?php $idx = 1; if (isset($this->careers)) : foreach ($this->careers as $careerName => $careerValue):?>
				<td width="50%">
          		<input type="checkbox" name="careers[]" value="<?=$careerName?>" class="careerslist"/>
				<?=$careerValue?></td>
	          	<?php if ($idx++%2 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr>
		</table></div>
		
		<!-- 选择经验语言 -->
		<div class="sel_disc">
			<h4 class="case_search_title"> <input type="checkbox" name="languagesAll" /> <?=$this->tr('please_choice_languages')?></h4>
			<div class="case_search_con">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
				<tr>
				<?php $idx = 1; if (!empty($this->languages)) : foreach ($this->languages as $languagesName => $languagesValue):?>
					<td width="50%">
	          		<input type="checkbox" name="languages[]" value="<?=$languagesName?>" class="languageslist"/>
		          	<?=$languagesValue?></td>
		          	<?php if ($idx++%2 == 0) :?>
		          		</tr><tr>
		          	<?php endif;?>
				<?php endforeach;endif;?>
				</tr>
			</table></div></div>
		
		<!-- 选择业务领域 -->
		<div class="sel_yw">
			<h4 class="case_search_title">  <input type="checkbox" name="industriesAll" /> <?=$this->tr('please_choice_industries')?></h4>
			<div class="case_search_con">
				<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
				<tr>
	            <?php $idx = 1; if (isset($this->industries)) : foreach ($this->industries as $industriesName => $industriesValue):?>
		          	<td width="50%">
		          		<input type="checkbox" name="industries[]" value="<?=$industriesName?>" class="industrieslist"/>
		          	<?=$industriesValue?></td>
		          	<?php if ($idx++%2 == 0) :?>
		          		</tr><tr>
		          	<?php endif;?>
				<?php endforeach;endif;?>
				</tr>
			</table></div></div>
		<br class="cls" />
		
		<!-- 选择勤务地 -->
		<h4 class="case_search_title"> <!-- <input type="checkbox" name="checkbox2" /> --><?=$this->tr('please_choice_workingplace')?></h4>
		<div class="address_t">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
			<tr><td>
				<input type="checkbox" name="japans" value="all" class="japan" />
				<?=$this->tr("Japan")?>
			</td></tr></table>
		</div>
		<div class="address_con">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_disc_search">
		  	<tr>
			<?php $idx = 1; if (isset($this->japan)) : foreach ($this->japan as $name => $value):?>
				<td width="25%">
				<input type="checkbox" name="workplace[]" class="japanlist" value="<?=$name;?>" />
				<?=$value?></td>
	          	<?php if ($idx++%4 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr></table>
		</div>
		<div class="address_t">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr><td>
            	<input type="checkbox" name="overseas" value="all" class="over" />
              	<?=$this->tr("OVERSEA")?>
			</td></tr></table>
		</div>
		<div class="address_con">
			<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_disc_search">
            <tr>
			<?php $idx = 1; if (isset($this->oversea)) : foreach ($this->oversea as $name => $value):?>
				<td width="25%">
				<input type="checkbox" name="workplace[]" class="overlist" value="<?=$name;?>" />
				<?=$value?></td>
	          	<?php if ($idx++%4 == 0) :?>
	          		</tr><tr>
				<?php endif;?>
			<?php endforeach;endif;?>
			</tr></table>
		</div>
		<div class="btn_search"><input type="image" id="btn_search" src="/img/default/front/<?=$auth->locale?>/btn_search.jpg" /></div>
	</div>
	</form>
</div>
<!--End: <div id="left">-->


<!-- 主页右侧 -->
<div id="right">
<?php if (empty($auth->usr)):?>
	<!-- 用户登陆 -->
	<h3 class="event_t"><? echo $this->tr('USR'), $this->tr('LOGIN')?></h3>
	<div class="enent_con">
		<form id="form_login_homepage">
			<table border="0">
			<tr><td height="24" colspan="2"><?=$this->tr('EMAIL')?>：</td></tr>
			<tr><td height="24" colspan="2"><input type="text" id="login_email_homepage" name="login_email" style="width:150px; height: 20px;" /></td></tr>
			<tr><td height="24" colspan="2"><?=$this->tr('PASSWORD')?>：</td></tr>
			<tr><td height="24" colspan="2"><input type="password" id="login_passwd_homepage" name="login_passwd" style="width:150px; height: 20px;" /></td></tr>
			<tr><td height="30" align="left"><input type="checkbox" name="isAutoLogin" value="Y" /> <?=$this->tr('AUTO_LOGIN')?></td></tr>
			<tr><td align="center" style="padding-top:5px;"><a id="btn_login_homepage" href="javascript:void(0);" class="ENABLED_Y"><img alt="Login" src="/img/default/front/<?=$auth->locale?>/btn_login.jpg" /></a></td></tr>			
			<tr>
				<td height="30" align="left">
					<a href="/front_register/register" target="_blank"><?=$this->tr('FREE_REGISTER')?></a>
					&nbsp;&nbsp;
					<a href="/front_passwd/passwd" target="_blank"><?=$this->tr('get_back_passwd')?></a>
				</td>
			</tr>
			</table>
		</form>
	</div>
<?php endif;?>
	<!-- 站内活动 -->
	<h3 class="event_t"><?=$this->tr('site_event')?></h3>
	<div class="enent_con">
		<ul class="c_12_01">
			<?if (isset($this->eventList) && !empty($this->eventList)):foreach ($this->eventList as $event): ?>
				<li><a href="/front_event/eventdetail/fid/<?=$event['id']?>" target="_blank"><?=$event['subject']?></a></li>
			<?endforeach;endif;?>
		</ul>
	</div>
	<!--ad-->
	<div class="marB" style="height: 200px; background-color: #e9e9e9;"></div>
	<div class="marB" style="height: 200px; background-color: #e9e9e9;"></div>
</div>
<br class="cls" />
</div>
<!--End: <div id="wraper">-->


<!-- ShareTo Button BEGIN -->
<div id="floatTools" class="share">
	<div class="floatL">
		<a href="javascript:void(0);" onclick="document.getElementById('pop_image').style.display='block'">
			<?=$this->tr('EXPAND')?>
		</a>
	</div>
	<div id="pop_image" class="floatR" style="display: none">
		<h4>
			<span class="fr"> 
				<a href="javascript:void(0);" onclick="document.getElementById('pop_image').style.display='none'"> 
					<img src="/img/default/front/<?=$auth->locale?>/close.gif" width="17" height="17" />
				</a>
			</span>
			<?=$this->tr('SHARE_TO')?>
		</h4>
		<ul class="weibo">
			<li class="sharetosina">
				<a href="javascript:void(0);" id="shareTo_tsina"><?=$this->tr('T_SINA')?></a>
			</li>
			<li class="sharetoqq">
				<a href="javascript:void(0);" id="shareTo_tqq"><?=$this->tr('T_QQ')?></a>
			</li>
			<li class="sharetoTwitter">
				<a href="javascript:void(0);" id="shareTo_twitter">Twitter</a>
			</li>
			<li class="sharetoFacebook">
				<a href="javascript:void(0);" id="shareTo_fb">Facebook</a>
			</li>
		</ul>
		<p><?=$this->tr('RECMD_TO_YOUR_FRIENDS__30_THOUSAND_YEN_WILL_BE_PAID_BACK__AFTER_INTERVIEW_SUCCESS')?></p>
		<input id="email_consignee" type="text" class="input_share"
			value="<?=$this->tr('please_input_email')?>" />
		<div class="share_btn">
			<a href="javascript:void(0);" id="btn_sendEmail">
				<img alt="" src="/img/default/front/<?=$auth->locale?>/btn_share.jpg" />
			</a>
		</div>
	</div>
</div>
<!-- ShareTo Button END -->


<script type="text/javascript">
	//请填写邮箱地址
	var please_input_email = '<?=$this->tr('please_input_email')?>';
</script>
<script src="/js/default/index.js" type="text/javascript"></script>