<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<div id="wraper">
	<h3 class="t_top"><?=$this->tr('MEMBER_BASEINFO_SETTING')?></h3>
	<div class="user_center">		
		<h3 class="note_t"><?=$this->tr('MEMBER_BASEINFO_SETTING')?></h3>	
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <td width="22%" align="right" bgcolor="#f7f7ff"><?=$this->tr('BELONG_COM')?>：</td>
            <td width="78%" bgcolor="#f7f7ff"><?=$this->lp['fullname']?></td>
          </tr>
          <tr>
            <td align="right" bgcolor="#f7f7ff"><?=$this->tr('USR_CODE')?>：</td>
            <td bgcolor="#f7f7ff" ><?=$this->resume['talent_code']?></td>
          </tr>          
        </table>
		<h3 class="note_t"><?=$this->tr('RESUME_SETTING')?></h3>	
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <td colspan="2" align="right" bgcolor="#f7f7ff">
            	<span class="resume_pre">
            		<a href="/usr_resume/previewresume/resumeCode/<?=$this->resume['code']?>" target="_blank"><?=$this->tr('resume_preview')?></a>
            	</span>
            </td>
          </tr>
          <tr>
            <td align="right" bgcolor="#f7f7ff" width="22%" ><?=$this->tr('BASE_INFO')?>：</td>
            <td bgcolor="#f7f7ff" class="fgrey">
            	<?=$this->tr('BIRTH_YEAR_MONTH_DAY__RESIDENCE__FINAL_DEGREE__ETC__MODIFY')?>
                <span class="btn_bg">
            		<a href="/usr_resume/modifyresume/resumeCode/<?=$this->resume['code']?>/anchor/baseinfo" target="_blank"><?=$this->tr('ALTER')?></a>
            	</span>
            </td>
          </tr>
          <tr>
            <td align="right" bgcolor="#f7f7ff"><?=$this->tr('EXPERIENCE_LANGUAGE')?>：</td>
            <td bgcolor="#f7f7ff" class="fgrey">
            	<?=$this->tr('SKILL_EXPERIENCE_MODIFY')?>
            	<span class="btn_bg">
            		<a href="/usr_resume/modifyresume/resumeCode/<?=$this->resume['code']?>/anchor/biz" target="_blank"><?=$this->tr('ALTER')?></a>
            	</span>
            </td>
          </tr>
          <tr>
            <td align="right" bgcolor="#f7f7ff"><?=$this->tr('PRJ_EXPERIENCE')?>：</td>
            <td bgcolor="#f7f7ff" class="fgrey">
            	<?=$this->tr('PRJ_EXPERIENCE_MODIFY')?>
            	<span class="btn_bg">
            		<a href="/usr_resume/modifyresume/resumeCode/<?=$this->resume['code']?>/anchor/prj" target="_blank"><?=$this->tr('ALTER')?></a>
            	</span>
            </td>
          </tr>
        </table>
		<h3 class="note_t"><?=$this->tr('OTHER_SETTING')?></h3>	
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <td width="22%" align="right" bgcolor="#f7f7ff"><?=$this->tr('OTHER_INFO')?>：</td>
            <td width="78%" bgcolor="#f7f7ff" class="fgrey">
            	<span class="btn_bg">
            		<a href="/usr_resume/modifyresume/resumeCode/<?=$this->resume['code']?>/anchor/other" target="_blank"><?=$this->tr('ALTER')?></a>
            	</span>
            	  <?=$this->tr('ABLE_WORK_DATE')?>：
            	  <?php if ($this->resume['able_work_date_choice'] == 'SPECIFY_DATE') {
            	  		echo $this->resume['able_work_date_choice'];
            	  	} else {
            	  		echo $this->tr($this->resume['able_work_date_choice']);
            	  	}
            	  ?>
            	  <br />
			      <?=$this->tr('current_biz_state')?>：<?=$this->tr('IS_APPLY_PRJ_' . $this->resume['is_apply_prj'])?>	
				<br />
			     <?=$this->tr('exp_unit_price')?>：<?=$this->resume['salary_exp']?><br />
			     <?=$this->tr('min_propose_price')?>：<?=$this->resume['salary_min']?><br />
			     <?=$this->tr('exp_workplace')?>：
			     <?php $expWorkplaces = json_decode($this->resume['exp_workplace']);
			     	if (!empty($expWorkplaces)) {
				     	foreach ($expWorkplaces as $expWorkplace) {
				     		echo $this->tr($expWorkplaces) . '&nbsp;&nbsp;';
				     	}
			     	}
			     ?>
			     <br />
			     <?=$this->tr('exp_prj_form')?>：<?=$this->tr($this->resume['exp_prj_form'])?><br />
			</td>
          </tr>
          <tr>
            <td align="right" bgcolor="#f7f7ff"><?=$this->tr('LP_REMARK')?>：</td>
            <td bgcolor="#f7f7ff"><?=$this->resume['remark_lp']?></td>
          </tr> 
		  <tr>
            <td align="right" bgcolor="#f7f7ff"><?=$this->tr('ADMIN_REMARK')?>：</td>
            <td bgcolor="#f7f7ff"><?=$this->resume['remark_admin']?></td>
          </tr>          
        </table>
		<h3 class="note_t"><?=$this->tr('RESUME_OPEN_SET')?></h3>
		<div class="tip" id="tip_isOpenResume"></div>
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <td width="22%" align="right" bgcolor="#f7f7ff"><?=$this->tr('IS_OPEN')?>：</td>
            <td width="78%" bgcolor="#f7f7ff">
				<span class="btn_bg"><a href="javascript:void(0);" id="btn_modifyIsOpenResume"><?=$this->tr('ALTER')?></a></span>
				<input type="radio" name="isOpenResume" value="Y" /><?=$this->tr('YES')?>
				<input type="radio" name="isOpenResume" value="N" /><?=$this->tr('NO')?>
 			</td>
          </tr>         
		</table>
  </div>
  <input id="resumeCode" type="hidden" value="<?=$this->resume['code']?>" />
</div>


<script type="text/javascript">
var isOpenResume = "<?=$this->resume['is_open']?>";
</script>
<script src="/js/admin/admin/usr/usr.js" type="text/javascript"></script>
