<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>
<div id="wraper">
	<h3 class="t_top">广告目录分类添加/编辑</h3>	
	<form id="form1" name="form1" method="post" action="">
  	<div class="info_modify">
	  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_info_modify">
        <tr>
          <td width="137" align="right">目录：</td>
          <td width="313"><input name="textfield" type="text" class="myinput" size="30" /></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>
            <img src="/img/default/front/<?=$auth->locale?>/btn_add.gif" class="marR" />
          </td>
        </tr>
      </table>
	</div>  
</form>
</div>