<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<form id="form1" name="form1" method="post" action="">

<!--start-->
<div class="search_result_lie02">
<h2 class="case_lie02_t"><span class="skim_num">浏览人数40人</span>JAVA人员紧急募集</h2>
<ul class="case_lie02_time">
<li>发布时间：2012-1-2</li>
<li>实效性：2012-1-2为止</li>
<li>发布公司：ID1234</li>
<li>发布公司名称：红星股份</li>
</ul>
<div class="case_lie02_con">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
    <tr>
      <td colspan="3">【业务要求】证券经验必须</td>
      </tr>
    <tr>
      <td colspan="3">【技术要求】JAVA5年以上经验</td>
      </tr>
    <tr>
      <td width="36%">【日语要求】1级以上水平</td>
      <td width="28%">【面谈次数】2回</td>
      <td width="36%" rowspan="5" align="center"></td>
    </tr>
    <tr>
      <td>【担当范围】基本设计开始</td>
      <td>【年龄要求】40以下</td>
      </tr>
    <tr>
      <td>【期间　　】2012/1/2～2012/12/30</td>
      <td>【国籍要求】无 </td>
      </tr>
    <tr>
      <td>【延长可能】有</td>
      <td>【单价　　】35万-45万日元</td>
      </tr>
    <tr>
      <td>【工作地点】东京 </td>
      <td>【精算　　】有</td>
      </tr>
  </table>
</div>  
  
</div>
<!--end-->
<div class="base_info_confirm">你是否真的应聘以上案件？</div>
<div class="btn_os">
	<a href="/lp_empapply/emplist" target="_blank">
		<img src="/img/default/front/<?=$auth->locale?>/btn_ok.jpg" width="80" height="30" class="btn_marR" />
	</a>
</div>
</form>
</div>
