<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<link href="/css/default/lp/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<div id="tablist1">
	<div class="case_search">
	<div class="search_left">
		<img src="/img/default/lp/<?=$auth->locale?>/icon_list_search.jpg" width="28" height="23" class="icon_search" />
		<select id="range" name="range" class="myselect">
			<option value="all"><?=$this->tr("EMP_ALL")?></option>
			<option value="code"><?=$this->tr("EMP_CODE")?></option>
			<option value="name"><?=$this->tr("EMP_NAME")?></option>
		</select>
		<label><input type="text" id="sValue" class="myinput" /></label>
		<label><input type="checkbox" name="checkbox" value="checkbox" /> <?=$this->tr("interview_has")?></label>
		<input type="image" id="searchBtn" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" />
	</div>
	</div>
</div>

<div class="search_result_lie01">
	<div id="caselist"></div>
	<div class="btn_os"><input id="selectBtn" type="image" src="/img/default/front/<?=$auth->locale?>/btn_select.jpg"/></div>
</div>

</div>
<script>
var manager, usrList;
$(function() {
	var caseCode = $('#form1').find("input[name='case_code']").val();
	$("#caselist").ligerGrid({
		checkbox: true,
        columns: [{display: USR_CODE, name: 'code', width:90},
                  {display: USR_NAME, name: 'fullname'},
                  {display: SEX, name: 'sexValue'},
                  {display: AGE, name: 'age', width:90},
                  {display: TEL_NUM, name: 'tel'},
                  {display: UPDATE_DATE, render: DateFunction, name: 'update_time'}/*,
                  {display: '相关操作', render: opFunction, align: "center", width:140}*/],
        url: '/front_apply/findemplist',
        //height: "auto", 
        width: "100%",
        columnWidth: 175,
        isScroll: false, frozen:false,
        //rowHeight: 
        //headerRowHeight: 
        detail: {onShowDetail: showDetail, height: "auto"},
        pageSize: 20
    });
    
	manager = $("#caselist").ligerGetGridManager();
	
	$("a[name='applyBtn']").click(function() {
		$("input[name='resume_code']").val($(this).parent().prevAll("td.code").text());
		$("#form1").submit();
	});
	
	function DateFunction(rowData, rowIndex) {
		return DateFormatFunction(rowData, 'update_time');
	}

	function opFunction(rowData, rowIndex) {
		return '<a href="javascript:void(0)" onclick="applyCase(null,\''+rowData.code+'\',\''+rowData.fullname+'\')">应聘</a>';
	}

	function showDetail(rowData, detailPanel){
		$("#detail").find("span[id]").each(function() {
			$(this).text(rowData[$(this).attr("id")]);
		});
		$(detailPanel).append($("#detail").html());
		$(detailPanel).find("#applyBtn").click(function() {
			doApplyCase([rowData]);
		});
		$(detailPanel).find("#viewBtn").click(function() {
			window.open("/usr_resume/previewresume/resumeCode/"+rowData['code']);
		});
	}

	$("#searchBtn").click(function() {
		var sValue = $("#sValue").val();
		var range = $("#range").val();
		manager.setOptions({parms: {"sValue": sValue, "range": range}});
    	manager.loadData();
	});

	$("#selectBtn").click(function() {
		var rows = manager.getSelecteds();
		doApplyCase(rows);
		return false;
	});
});


function doApplyCase(rows) {
	if (!rows || rows.length == 0) {
		alert(PLEASE_CHOISE_APPLY_EMP);
		return false;
	}
	rows = rows || [{code: empCode, fullname: empName}];
	var html = ['<div style="width:500px;"><div class="notice_con">'+SURE_CHOISE_APPLE_CASE+'</div>'];
	html.push('<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_del">');
	html.push('<tr>');
	html.push('<th width="25%">'+EMP_CODE+'</th>');
	html.push('<th width="75%" align="left"> '+EMP_NAME+'</th>');
	html.push('</tr>');
	$.each(rows, function(i, v) {
		html.push('<tr>');
		html.push('<th width="25%">'+v.code+'</th>');
		html.push('<th width="75%" align="left"> '+v.fullname+' </th>');
		html.push('</tr>');
	});
	html.push('</table>');
	html.push('</div>');
	html = html.join("");
	ligerConfirm(TITLE_APPLY_CASE, html, {width: 550}, function() {
		var ids = "";
		$.each(rows, function(i, v) {
			ids += v.code;
			ids += ",";
		});
		ids = ids.substring(0, ids.length-1);
		window.location.href = "/front_apply/applycaseconfirm/caseCode/<?=$this->caseCode?>/resumes/"+ids;
		/*$.ajax({
			url: '/front_apply/applycaseforlp',
			type: 'post',
			async: false,
			dataType: 'json', //xml, json, script or html
			data: {ids: ids, caseCode: $('#form1').find("input[name='case_code']").val()},
			success: function(data, textStatus, jqXHR) {
				if (data['err'] == 0) {
					alert(data['msg'], null, 'none');
					$("#searchBtn").click();
				} else {
					alert(data['msg']);
				}
			}
		});*/
	});
}
</script>

<div id="detail" style="display: none;">
	<div class="search_result_lie02">
		<ul class="case_lie02_time">
			<li><?=$this->tr('USR_NAME')?>：<span class="fblue" id='fullname'></span></li>
			<li><?=$this->tr('SEX__')?>：<span class="fblue" id='tr_sex'></span></li>
			<li><?=$this->tr('AGE')?>：<span class="fblue" id='age'></span></li>
			<li><?=$this->tr('CONTACT_WAY')?>：<span class="fblue" id='tel'></span></li>
			<li><?=$this->tr('UPDATE_DATE')?>：<span class="fblue" id='update_date'></span></li>
		</ul>
		<div class="case_lie02_con">
			<table style="width:100%" border="0" cellspacing="0" cellpadding="0" class="tab_faren_case">
				<tr>
					<td width="36%"><strong><?=$this->tr('EXPERIENCE_AND_JP_EXPERIENCE')?>：</strong><span id='experience'></span></td>
					<td width="28%"><strong><?=$this->tr('BIZ')?>：</strong><span id='biz'></span></td>
					<td width="36%"><strong><?=$this->tr('SKILL')?>：</strong><span id='skill'></span> </td>
				</tr><tr>
					<td><strong><?=$this->tr('JPL')?>：</strong><span id='ja_ability'></span></td>
					<td><strong><?=$this->tr('able_work_status')?>：</strong><span id='adjust_able_work_date'></span></td>
					<td><strong><?=$this->tr('ACCEPT_UNIT_PRICE_RANGE')?>：</strong><span id='salary_display'></span> </td>
				</tr><tr>
					<td colspan="3"><strong><?=$this->tr('REMARK')?>：</strong><span id='pr'></span></td>
				</tr><tr><td colspan="3">
					<a href="javascript:void(0)" id="applyBtn">
						<img  src="/img/default/front/<?=$auth->locale?>/btn_apply.jpg" width="76" height="26" class="marR" />
					</a><a href="javascript:void(0)" id="viewBtn">
						<img src="/img/default/lp/<?=$auth->locale?>/btn_preview.jpg" width="80" height="30" class="marR" />
					</a>
				</td></tr>
			</table>
		</div>
	</div>
</div>
<form id="form1" name="form1" method="post" action="/front_apply/applycase" style="display:none">
	<input type="hidden" name="case_code" value="<?=$this->caseCode?>"/>
	<input type="hidden" name="emp_list" value='<?=json_encode($this->empList)?>'/>
</form>