<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<div class="case_search_con">
		  <select name="select2" class="select_w160">
		    <option>姓名</option>
	      </select>
		  <input type="text" name="textfield" class="myinput_w360" />
		  <a href="javascript:void(0);">
		  	<img alt="检索" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" />
		  </a>
	</div>
	<form id="form1" name="form1" method="post" action="">
	<div class="case_search_expand">
	<div class="case_lie02_time">

	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="35"><input type="checkbox" name="checkbox" value="checkbox" /> 用户ID：<span class="fblue">CUS1210001</span></td>
          <td>用户名：<span class="fblue">欧阳 太郎</span></td>
          <td>性别：<span class="fblue">男</span></td>
          <td>年龄：<span class="fblue">36岁</span></td>
          <td>联络方式：<span class="fblue">12364887414</span></td>
          <td>更新日：<span class="fblue">20111201</span></td>
        </tr>
      </table>
	</div>
<div class="case_lie02_con">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_user_list">
    <tr>
      <td width="36%"><strong>经验及日本经验：</strong> 10年(3年日本)</td>
      <td width="28%"><strong>业务：</strong>证券2年  流通1年</td>
      <td width="36%"><strong>技术：</strong> java  4年/C# 2年/VB 1年 </td>
    </tr>
    <tr>
      <td><strong>日语：</strong>ビジネスレベル</td>
      <td><strong>稼动状态：</strong>可移动日：20111201～</td>
      <td><strong>可接受单价范围：</strong>40万～45万 </td>
    </tr>
    <tr>
      <td colspan="3"><strong>备注：</strong>
      	阿里斯顿咖啡机阿斯顿克里夫夹啊设立考点附近阿斯顿离开房间啊；上的浪费空间啊
      </td>
      </tr>
    <tr>
      <td colspan="3">
      	<a href="/lp_empresume/previewresume" target="_blank">
	      <img src="/img/default/lp/<?=$auth->locale?>/btn_preview.jpg" width="80" height="30" class="marR" />
	    </a>
      	<a href="/lp_emp/empedit" target="_blank">
	      <img src="/img/default/lp/<?=$auth->locale?>/btn_edit.jpg" width="80" height="30" class="marR" />
	    </a>
	    <a href="/lp_emp/delemp" target="_blank">
	      <img src="/img/default/lp/<?=$auth->locale?>/btn_del01.jpg" width="80" height="30" class="marR" />
	     </a>
	    <a href="/lp_emp/empapplystatus" target="_blank">
	      <img src="/img/default/lp/<?=$auth->locale?>/btn_look.jpg" width="110" height="30" />
	     </a>
      </td>
      </tr>
  </table>
</div>  
  </div>
  <div class="btn_os">
  <a href="/lp_empapply/empapply" target="_blank">
  	<img alt="应聘" src="/img/default/front/<?=$auth->locale?>/btn_tian.jpg" class="btn_marR" />
  </a>
  <input type="image" name="imageField2" src="/img/default/front/<?=$auth->locale?>/btn_select_del.jpg" />
  <div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div> 
</form>
</div>