<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>

<div id="wraper">
	<h3 class="t_top">应聘取消</h3>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_judge">
    <tr>
      <th width="11%" align="left">案件ID</th>
      <th width="25%">案件名</th>
      <th width="13%">取消者</th>
      <th width="13%">取消阶段</th>
      <th width="16%">理由选择（必须）</th>
      <th width="22%" align="left">其他（可不填写）</th>
    </tr>
    <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
    </tr>
	  <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
      </tr>
	  <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
      </tr>
	  <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
      </tr>
	  <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
      </tr>
	  <tr>
      <td align="left">A000001</td>
      <td align="center">JAVA人员募集</td>
      <td align="center">法人</td>
      <td align="center">应聘中</td>
      <td align="center">
        <label>
          <select name="select" class="myselect">
            <option>技术不足</option>
            <option>日语不足</option>
            <option>经验不足</option>
            <option>其它</option>
          </select>
        </label>      </td>
      <td align="left"><label>
        <input type="text" name="textfield" class="myinput" />
      </label></td>
      </tr>
  </table>
  <div class="btn_os">
  <label>
  <input type="image" name="imageField" src="/img/default/front/<?=$auth->locale?>/btn_qd.jpg" class="marR" />
  </label>
  <label>
  <input type="image" name="imageField2" src="/img/default/front/<?=$auth->locale?>/btn_back.jpg" />
  </label>    
</div>
</div>