<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<form id="form1" name="form1" method="post" action="">
 <h3 class="notice_t">
 <span class="notice_os">
   <img src="/img/default/front/<?=$auth->locale?>/btn_msg_del.jpg" width="48" height="25" /> </span>消息通知</h3>
 <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#a3a3a3" class="tab_msg">
   <tr>
     <th>&nbsp;</th>
     <th align="left">件名</th>
     <th>受信日</th>
     <th style="text-align: center;"><input type="checkbox" name="checkbox10" value="checkbox" /></th>
   </tr>
   <tr class="new">
     <td align="center"><img src="/img/default/lp/<?=$auth->locale?>/email_small.jpg" width="18" height="14" /></td>
     <td><a href="#" target="_blank">JAVA案件给您了面试调整，请确认</a></td>
     <td align="center"> 2012年3月30日</td>
     <td align="center">
         <input type="checkbox" name="checkbox" value="checkbox" />
     </td>
   </tr>
   <tr class="new">
     <td align="center"><img src="/img/default/lp/<?=$auth->locale?>/email_small.jpg" width="18" height="14" /></td>
     <td><a href="#" target="_blank">JAVA案件给您了面试调整，请确认</a></td>
     <td align="center"> 2012年3月30日</td>
     <td align="center">
       <input type="checkbox" name="checkbox2" value="checkbox" />
     </td>
   </tr>
   <tr class="readed">
     <td align="center"><img src="/img/default/lp/<?=$auth->locale?>/email_small.jpg" width="18" height="14" /></td>
     <td><a href="#" target="_blank">JAVA案件给您了面试调整，请确认</a></td>
     <td align="center"> 2012年3月30日</td>
     <td align="center">
       <input type="checkbox" name="checkbox4" value="checkbox" />
     </td>
   </tr>
   <tr class="readed">
     <td align="center"><img src="/img/default/lp/<?=$auth->locale?>/email_small.jpg" width="18" height="14" /></td>
     <td><a href="#" target="_blank">JAVA案件给您了面试调整，请确认</a></td>
     <td align="center"> 2012年3月30日</td>
     <td align="center">
       <input type="checkbox" name="checkbox5" value="checkbox" />
     </td>
   </tr>
 </table>
 <div class="btn_os">
  <div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
  </form>
</div>