<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<div id="wraper">
	<h3 class="t_top"><?=$this->tr('send_msg')?></h3>
	<div class="tip" id="tip_msg"></div>
	<form id="form_sendMsg">
		<table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e5e5e5" class="tab_msg">
	        <tr>
	          <th width="18%" align="right"><?=$this->tr('SEND_OBJECT')?></th>
	          <td width="82%">
	            <input type="checkbox" name="recvers[]" value="LP" /><?=$this->tr('LP')?>
				<input type="checkbox" name="recvers[]" value="MEMBER" /><?=$this->tr('INVIDIDUAL')?>
				<input type="checkbox" name="recvers[]" value="ASSIST" /><?=$this->tr('ASSIST')?>
			  </td>
	        </tr>
	        <tr>
	          <th align="right"><?=$this->tr('TITLE')?></th>
	          <td><input type="text" id="title" maxlength="64" name="title" size="64" value="" style="height: 24px;" /></td>
	        </tr>
	        <tr>
	          <th align="right"><?=$this->tr('CONTENT')?></th>
	          <td><textarea id="content" name="content" class="mytextarea"></textarea></td>
	        </tr>
			<tr>
	          <th align="right"></th>
	          <td>
	            <a href="javascript:void(0);" id="btn_save">
		            <img src="/img/admin/<?=$auth->locale?>/btn_keep.jpg" />
	            </a>
	            <a href="javascript:void(0);" id="btn_send">
	            	<img src="/img/admin/<?=$auth->locale?>/btn_send.jpg" />
	            </a>
	          </td>
	        </tr>
		</table>
		<!-- 隐藏变量 -->
		<input type="hidden" id="msId" name="msId" value="" />
	</form>
</div> <!-- <div id="wraper"> -->




<script type="text/javascript">
	var oMs = <?=$this->jsMs?>;
</script>
<script src="/js/admin/msg/sendmsg.js" type="text/javascript"></script>
