<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<div id="wraper">
	<div class="top_search">
	<form id="form2" name="form2" method="post" action="">
	<ul>
	<li><img src="/img/admin/<?=$auth->locale?>/search_t.gif" width="28" height="23" /></li>
	<li><label>
		  <select name="select" class="myselect">
		    <option>全部</option>
	      </select>
		  </label>
	</li>
	<li><label><input type="text" name="textfield" class="myinput" /></label></li>
	<li>
	  
	    <label>
	      <input type="image" name="imageField3" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" />
	      </label>
	</li>
	</ul>
	</form>
  </div>
	<div class="search_term"><a href="/admin/admin_casecollect/collectcasesearch" target="_blank">
		<span class="case_lie">案件列表</span></a>
		<span class="fr marR">共 <font class="fred">10</font> 个案件</span>
	</div>
	<div class="search_result_lie02">
<h2 class="case_lie02_t"><span class="skim_num">浏览人数40人</span>JAVA人员紧急募集</h2>
<ul class="case_lie02_time">
<li>发布时间：2012-1-2</li>
<li>实效性：2012-1-2为止</li>
<li>发布公司：ID1234</li>
<li>发布公司名称：红星股份</li>
</ul>
<div class="case_lie02_con">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
    <tr>
      <td colspan="3">【业务要求】证券经验必须</td>
      </tr>
    <tr>
      <td colspan="3">【技术要求】JAVA5年以上经验</td>
      </tr>
    <tr>
      <td width="41%">【日语要求】1级以上水平</td>
      <td width="38%">【面谈次数】2回</td>
      <td width="21%" rowspan="5" align="center">
      	<a href="/admin/admin_casecollect/collectcaseconfirm">
      		<img src="/img/default/front/<?=$auth->locale?>/btn_collection_invite.jpg" width="80" height="30" />
      	</a>
      </td>
    </tr>
    <tr>
      <td>【担当范围】基本设计开始</td>
      <td>【年龄要求】40以下</td>
      </tr>
    <tr>
      <td>【期间　　】2012/1/2～2012/12/30</td>
      <td>【国籍要求】无 </td>
      </tr>
    <tr>
      <td>【延长可能】有</td>
      <td>【单价　　】35万-45万日元</td>
      </tr>
    <tr>
      <td>【工作地点】东京 </td>
      <td>【精算　　】有</td>
      </tr>
  </table>
</div>  
  
</div>

<div class="search_result_lie02">
<h2 class="case_lie02_t"><span class="skim_num">浏览人数40人</span>JAVA人员紧急募集</h2>
<ul class="case_lie02_time">
<li>发布时间：2012-1-2</li>
<li>实效性：2012-1-2为止</li>
<li>发布公司：ID1234</li>
<li>发布公司名称：红星股份</li>
</ul>
<div class="case_lie02_con">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
    <tr>
      <td colspan="3">【业务要求】证券经验必须</td>
      </tr>
    <tr>
      <td colspan="3">【技术要求】JAVA5年以上经验</td>
      </tr>
    <tr>
      <td width="41%">【日语要求】1级以上水平</td>
      <td width="38%">【面谈次数】2回</td>
      <td width="21%" rowspan="5" align="center"><img src="/img/default/front/<?=$auth->locale?>/btn_collection_invite.jpg" width="80" height="30" /></td>
    </tr>
    <tr>
      <td>【担当范围】基本设计开始</td>
      <td>【年龄要求】40以下</td>
      </tr>
    <tr>
      <td>【期间　　】2012/1/2～2012/12/30</td>
      <td>【国籍要求】无 </td>
      </tr>
    <tr>
      <td>【延长可能】有</td>
      <td>【单价　　】35万-45万日元</td>
      </tr>
    <tr>
      <td>【工作地点】东京 </td>
      <td>【精算　　】有</td>
      </tr>
  </table>
</div>  
</div>

<!--page-->
<div class="btn_os"><div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
</div>
<!--page-->
<!--end-->
</div>
