<SCRIPT LANGUAGE="JavaScript">
window.onload = function() {
    doubleBgColor(document.getElementById("tab_list"),"#f3f3f3","#FFFFFF");
}

function doubleBgColor(Table,Bg1,Bg2) {
    for (var i=0;i<Table.rows.length;i++) Table.rows[i].bgColor=i%2?Bg2:Bg1;
}
</SCRIPT>
<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
  <h3 class="msg_title">应聘案件确认</h3>
  <div class="notice_con">你确定要应聘以下的案件？</div>
  <div class="user_case_list">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_list" class="tab_user_case">
    <tr>
      <th width="24%" align="center">案件ID</th>
      <th width="76%" align="left">案件名</th>
      </tr>
    <tr>
      <td align="center">A000001</td>
      <td align="left">JAVA人员募集</td>
      </tr>
	  <tr>
      <td align="center">A000001</td>
      <td align="left">JAVA人员募集</td>
      </tr>
  </table>  
</div>
<div class="btn_os">
  <img src="/img/default/front/<?=$auth->locale?>/btn_offer.jpg" width="80" height="30" class="btn_marR" />
  <div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>
  </div>
</div>