<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
	$auth = new Zend_Session_Namespace('AUTH');
?>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--  <title>Outsourcing2</title>-->
	<?php include_once 'inc/adminheader.phtml';?>
	<?=$this->headTitle(); ?>
	<?=$this->headLink(); ?>
	<?=$this->headLink()->appendStylesheet("/css/global.css"); ?>
	<?=$this->headStyle(); ?>
	<?=$this->headScript(); ?>
	<link href="/css/admin/admin/css.css" rel="stylesheet" type="text/css" />
	<link href="/js/jquery/ui/themes/redmond/jquery-ui-1.8.21.custom.css" rel="stylesheet" type="text/css" />
	<link href="/js/jquery/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
<!--	<link href="/js/jquery/ligerUI/skins/Gray/css/grid.css" rel="stylesheet" type="text/css" />-->
	<script src="/js/jquery/jquery-1.7.2.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.dropdown.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.form.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.blockUI.js" type="text/javascript"></script>
	<script src="/js/jquery/ui/jquery-ui-1.8.21.custom.js" type="text/javascript"></script>
	<script src="/js/jquery/ui/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
	<script src="/js/jquery/ligerUI/js/ligerui.all.js" type="text/javascript"></script>
<!--	<script src="/js/jquery/ligerUI/js/ligerui.min.js" type="text/javascript"></script>-->
	<script src="/js/ckeditor/ckeditor.js" type="text/javascript"></script>
	<script src="/js/global.js" type="text/javascript"></script>
	<script src="/js/util.js" type="text/javascript"></script>
</head>
<body>
<div id="container">
	<div id="header">
		<img src="/img/admin/<?=$auth->locale?>/logo.jpg" width="401" height="63" class="logo" />
		<div class="login_info">
			<!-- 欢迎管理员-->
			<?php if (isset($auth->usr)):?>
				<div>
					<?=$this->tr('welcome')?>，<?=$auth->usr['nickname']?>
					&nbsp;&nbsp;<a href="javascript:void(0);" id="btn_admin_logout"><?=$this->tr('logout')?></a>
				</div>
			<?php endif;?>
		</div>
		<div style="clear:both;"></div>
		<div class="nav">
			<ul class="dropdown">
				<li><a href="javascript:void(0);"><? echo $this->tr('CENTER'), $this->tr('MGT')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_index" target="_self"><? echo $this->tr('HOMEPAGE')?></a></li>
						<li><a href="/admin/admin_file/uploadfilemgt" target="_self"><? echo $this->tr('FILE'), $this->tr('MGT')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('MSG'), $this->tr('CENTER')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/msg/msglist" target="_self"><? echo $this->tr('MSG'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/admin/msg/sendmsg" target="_self"><? echo $this->tr('SEND'), $this->tr('MSG')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('CASE'), $this->tr('MGT')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_casesearch/casesearch" target="_self"><? echo $this->tr('CASE'), $this->tr('SEARCH')?></a></li>
						<li><a href="/admin/admin_case/createcase" target="_self"><? echo $this->tr('APPEND'), $this->tr('NEW'), $this->tr('CASE')?></a></li>
						<li><a href="/admin/admin_casecollect/incollectcaselist" target="_self"><? echo $this->tr('CASE'), $this->tr('APPLY'), $this->tr('STATE'), $this->tr('MGT')?></a></li>
						<li><a href="/admin/admin_caseunpublish/unpublishcaselist" target="_self"><? echo $this->tr('UNRELEASE'), $this->tr('CASE'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/admin/admin_caseinterest/interestcaselist" target="_self"><? echo $this->tr('BE_INTERESTED_IN'), $this->tr('CASE'), $this->tr('GENERAL_VIEW')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('EMP'), $this->tr('MGT')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_usr/searchusr" target="_self"><? echo $this->tr('EMP'), $this->tr('SEARCH')?></a></li>
						<li><a href="/usr_resume/createresume" target="_self"><? echo $this->tr('EMP'), $this->tr('LOGIN')?></a></li>
						<li><a href="/admin/admin_usr/applycasemgt" target="_self"><? echo $this->tr('EMP'), $this->tr('APPLY'), $this->tr('CASE'), $this->tr('STATE'), $this->tr('MGT')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('LP'), $this->tr('MGT')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_lp/lplist" target="_self"><? echo $this->tr('LP'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/front_lpreg/lpreg" target="_self"><? echo $this->tr('LP'), $this->tr('LOGIN')?></a></li>
						<li><a href="/admin/akb/depositakb" target="_self"><? echo $this->tr("LP_DEPOSIT_AKB_QUERY")?></a></li>
						<li><a href="/admin/akb/consumeakb" target="_self"><? echo $this->tr("LP_HISTORY_CONSUME_DETAIL")?></a></li>
						<li><a href="/admin/admin_editor/editorlist" target="_self"><? echo $this->tr('DATA'), $this->tr('EDITOR'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/admin/admin_editor/addeditor" target="_self"><? echo $this->tr('DATA'), $this->tr('EDITOR'), $this->tr('LOGIN')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('OTHER'), $this->tr('SETTING')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_admin/adminset" target="_self"><? echo $this->tr('MGR'), $this->tr('SETTING')?></a></li>
						<li><a href="/admin/admin_admin/batchset" target="_self"><? echo $this->tr('BATCH'), $this->tr('SETTING')?></a></li>
						<li><a href="/admin/admin_email/emailset" target="_self"><? echo $this->tr('EMAIL'), $this->tr('SETTING')?></a></li>
						<li><a href="/admin/admin_email/emailtpllist" target="_self"><? echo $this->tr('EMAIL'), $this->tr('TPL')?></a></li>
						<li><a href="/admin/admin_price/priceset" target="_self"><? echo $this->tr('PRICE'), $this->tr('SETTING')?></a></li>
					</ul>
				</li>
				<li><a href="javascript:void(0);"><? echo $this->tr('EVENT'), $this->tr('AD'), $this->tr('MTC')?></a>
					<ul class="sub_menu">
						<li><a href="/admin/admin_event/eventlist" target="_self"><? echo $this->tr('EVENT'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/admin/admin_event/initiateevent" target="_self"><? echo $this->tr('EVENT'), $this->tr('LOGIN')?></a></li>
						<li><a href="/admin/admin_event/eventcatalog" target="_self"><? echo $this->tr('EVENT'), $this->tr('CATALOG')?></a></li>
						<li><a href="/admin/admin_ad/ad" target="_self"><? echo $this->tr('HOMEPAGE'), $this->tr('AD')?></a></li>
						<li><a href="/admin/admin_ad/adlist" target="_self"><? echo $this->tr('AD'), $this->tr('GENERAL_VIEW')?></a></li>
						<li><a href="/admin/admin_ad/createad" target="_self"><? echo $this->tr('AD'), $this->tr('LOGIN')?></a></li>
						<li><a href="/admin/admin_ad/adcatalog" target="_self"><? echo $this->tr('AD'), $this->tr('CATALOG')?></a></li>
					</ul>
				</li>
				<li><a href="http://new.cnzz.com/v1/login.php?siteid=4988774" target="_blank">
						<? echo $this->tr('DATA'), $this->tr('STATS')?>
					</a>
				</li>
			</ul>
		</div>
		<div style="clear:both;"></div>

	    <!--网站浏览跟踪 ，顶部第3层 -->
	    <div id="header_crumb" style="margin: 5px; text-align: left;">
	    	<?=$this->tr('CURR_PLACE')?>：
	    	<?php
	    	if (isset($this->layout()->crumbs)):
    		$crumbs = $this->layout()->crumbs;
	    	?>
	        <a href="/admin/admin_index" target="_self"><?=$this->tr('HOMEPAGE')?></a>
	        <?php for ($i = 0; $i < count($crumbs); $i++):?>
	        	<?php if ($i == count($crumbs)-1):?>
	        	 &gt; <?=$crumbs[$i]['name']?>
	        	<?php else:?>
	        	 &gt; <a href="<?=$crumbs[$i]['uri']?>"><?=$crumbs[$i]['name']?></a>
	        	<?php endif;?>
	        <?php endfor;?>
	        <?php endif;?>
	    </div>
	</div>
	<div style="clear:both;"></div>

	<!-- content -->
	<div id="body_content" style="margin-top: 24px; text-align: left;">
		<?=$this->layout()->content ?>
	</div>

	<!-- footer -->
	<div id="footer">
		<div class="link"><a href="#"><?=$this->tr('ABOUT_US')?></a>
			|  <a href="/front_advantage/advantage"><?=$this->tr('our_advantage')?></a>
			|  <a href="/front_contact/contact"><?=$this->tr('ADVISORY')?></a>
		</div>
		<div>Copyright www.jinzai-anken.com <?=$this->tr('ALL_RIGHT_RESERVED')?></div>
		<div><script src="http://s21.cnzz.com/stat.php?id=4988774&web_id=4988774&show=pic" type="text/javascript"></script></div>
	</div>
	<?php include_once 'inc/login.phtml';?>
</div>
<script type="text/javascript">
	var PROMPT = "<?=$this->tr('PROMPT')?>";
</script>
</body>
</html>