<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<!--<=$this->doctype()?>-->
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--  <title>Outsourcing2</title>-->
	<?php include_once 'inc/adminheader.phtml';?>
	<?=$this->headTitle(); ?>
	<?=$this->headLink(); ?>
	<?=$this->headLink()->appendStylesheet("/css/global.css"); ?>
	<?=$this->headStyle(); ?>
	<?=$this->headScript(); ?>
	
	<? if ($auth->locale == 'ja_JP'):?>
		<link href="/css/default/header_jp.css" rel="stylesheet" type="text/css" />
	<? else:?>
		<link href="/css/default/header_cn.css" rel="stylesheet" type="text/css" />
	<? endif;?>
<!--	<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />-->
	<link href="/js/jquery/ui/themes/redmond/jquery-ui-1.8.21.custom.css" rel="stylesheet" type="text/css" />
	<link href="/js/jquery/ligerUI/skins/Aqua/css/ligerui-all.css" rel="stylesheet" type="text/css" />
<!--	<link href="/js/jquery/ligerUI/skins/Gray/css/grid.css" rel="stylesheet" type="text/css" />-->
	<script src="/js/jquery/jquery-1.7.2.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.dropdown.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.form.js" type="text/javascript"></script>
	<script src="/js/jquery/jquery.blockUI.js" type="text/javascript"></script>
	<script src="/js/jquery/ui/jquery-ui-1.8.21.custom.js" type="text/javascript"></script>
	<script src="/js/jquery/ui/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
	<script src="/js/jquery/ligerUI/js/ligerui.all.js" type="text/javascript"></script>
<!--	<script src="/js/jquery/ligerUI/js/ligerui.min.js" type="text/javascript"></script>-->
	<script src="/js/ckeditor/ckeditor.js" type="text/javascript"></script>
	<script src="/js/global.js" type="text/javascript"></script>
	<script src="/js/util.js" type="text/javascript"></script>
</head>
<body>
	<div id="container">
		<div id="header">
			<!-- 网站logo，顶部左侧 -->
		    <div class="logo"><img src="/img/default/front/<?=$auth->locale?>/logo.jpg" width="394" height="67" /></div>
			<!-- 广告、语言选择、登陆、注册等，顶部右侧 -->
			<div class="top_r">
				<!-- 广告 -->
				<div class="top_ad">
					<a href="/front_ad/ad" target="_blank">
<!--						<img src="/img/default/front/<?=$auth->locale?>/top_ad.jpg" width="380" height="50" />-->
					</a>
				</div>
				<!-- 语言选择 -->
				<div class="top_link">
					<a href="javascript:setLang('ja_JP');"><?=$this->tr('JAPANESE')?></a> 
					| <a href="javascript:setLang('zh_CN');"><?=$this->tr('CHINESE')?></a>
				</div>
				<br class="cls" />
				<!-- 登陆或欢迎用户-->
				<?php if (!empty($auth->usr)):?>
					<div id="div_welcome" class="top_login_info">
						<?=$this->tr('welcome')?>，<?=$auth->usr['role_code']=='LP' ? $auth->usr['fullname'] : $auth->usr['fullname']?>
						&nbsp;&nbsp;<a href="javascript:void(0);" id="btn_logout"><?=$this->tr('logout')?></a>
					</div>
				<?php else:?>
					<div id="div_login" class="top_login_info" style="height:50px!important;line-height:24px;">
						<form id="form_login">
						<span style="float:left;"><?=$this->tr('EMAIL')?>:<input type="text" id="login_email" name="login_email" class="login_input" style="width:110px;" /></span>
						<span style="float:left;"><?=$this->tr('PASSWORD')?>:<input type="password" id="login_passwd" name="login_passwd" class="login_input" style="width:100px;" /></span>
						<span style="float:left;margin-right:5px;"><a id="btn_login" href="javascript:void(0);" class="ENABLED_Y"><img alt="Login" src="/img/default/front/<?=$auth->locale?>/btn_login.jpg" /></a></span>
						<span style="float:left;"><input type="checkbox" name="isAutoLogin" value="Y" style="margin-right:5px;" /><?=$this->tr('AUTO_LOGIN')?></span>
						</form>
					</div>
				<?php endif;?>
				
			</div>
			<br class="cls" />
			<!-- 导航次顶部 -->
			<div class="mainnav">
				<ul id="tabs">
					<li class="on"><a href="/?pwd=10" target="_blank"><span><?=$this->tr('HOMEPAGE')?></span></a></li>
					<li><a href="/front_case/case" target="_blank"><span><?=$this->tr('case_search')?></span></a></li>
					<li><a href="/front_talent/talent" target="_blank"><span><?=$this->tr('talent_search')?></span></a></li>
					<li><a href="/front_japan/japan" target="_blank"><span><?=$this->tr('go_to_japan')?></span></a></li>
					<li><a href="/front_event/event" target="_blank"><span><?=$this->tr('site_event')?></span></a></li>
					<li><a href="/front_advantage/advantage" target="_blank"><span><?=$this->tr('our_advantage')?></span></a></li>
					<li><?php if (isset($auth->usr)) {
							switch ($auth->usr["role_code"]) {
								case 'LP':
									$mypage = '/lp_lp/lp';
									break;
								case 'MEMBER':
									$mypage = '/usr_usr/usr';
									break;
								default:
									$mypage = '/';
									break;
							}
						} else {
							$mypage = '/';
						}
						?>
						<a href="<?=$mypage?>" target="_blank"><span>MYPAGE</span></a>
					</li>
				</ul>
			</div>
			<div style="clear:both;"></div>
		    
		    <!--网站浏览跟踪 ，顶部第3层 -->
		    <div id="header_crumb" style="margin: 5px;">
		    	<?=$this->tr('CURR_PLACE')?>：
		    	<?php 
		    	if (isset($this->layout()->crumbs)):
		    		$crumbs = $this->layout()->crumbs;
		    	?>
		        <a href="/?pwd=10" target="_blank"><?=$this->tr('HOMEPAGE')?></a>
		        <?php for ($i = 0; $i < count($crumbs); $i++):?>
		        	<?php if ($i == count($crumbs)-1):?>
		        	 &gt; <?=$crumbs[$i]['name']?>
		        	<?php else:?>
		        	 &gt; <a href="<?=$crumbs[$i]['uri']?>" target="_blank"><?=$crumbs[$i]['name']?></a>
		        	<?php endif;?>
		        <?php endfor;?>
		        <?php endif;?>
		    </div>
		</div>
		<div style="clear:both;"></div>
	
		<!-- content -->
		<div id="body_content" style="margin-top: 24px;">
			<?=$this->layout()->content ?>
		</div>
	
		<!-- footer -->
		<div id="footer">
			<div class="link"><a href="#" target="_blank"><?=$this->tr('ABOUT_US')?></a>  
				|  <a href="/front_advantage/advantage" target="_blank"><?=$this->tr('our_advantage')?></a>  
				|  <a href="/front_contact/contact" target="_blank"><?=$this->tr('contact_us')?></a>
			</div>
			<div>Copyright www.jinzai-anken.com <?=$this->tr('ALL_RIGHT_RESERVED')?></div>
			<div><script src="http://s21.cnzz.com/stat.php?id=4988774&web_id=4988774&show=pic" type="text/javascript"></script></div>
		</div>
		
		<?php include_once 'inc/login.phtml';?>
	</div> <!-- <div id="container"> -->
</body>
</html>