<div id="content">
	<div id="tip_genSql" class="tip"></div>
	<div>请输入用于生成插入SQL语句的表名，及字段名（用逗号分隔）：</div>
	<div>表名：<input id="tableName" type="text" value="" /></div>
	<div>字段名：<input id="fieldNames" type="text" value="" /></div>
	<div><button id="btn_genSql" type="button">生成INSERT SQL</button></div>
	<div><textarea id="ta_sql" rows="8" cols="100"></textarea></div>
</div>

<script src="/js/default/test/table/table.js" type="text/javascript"></script>