<?php 
	$auth = new Zend_Session_Namespace ( 'AUTH' ); 
	$role = isset($auth->usr) ? $auth->usr["role_code"] : NULL;
	$code = isset($auth->usr) ? $auth->usr["code"] : NULL;
?>
<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<link href="/css/jquery/jquery.pagination.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<?php if ($role == 'MEMBER'):?>
<?php include_once 'inc/centerheader.phtml';?>
<?php endif;?>
<h1 class="event_detial_t"><?=$this->detail ['subject']?></h1>
<div id="tab2">
<ul>
	<li id="t1" class="now"><?=$this->tr('EVENT')?></li>
	<li id="t2"><?=$this->tr('EVENT_MEMBER')?></li>
	<li id="t3"><?=$this->tr('EVENT_MESSAGE')?></li>
</ul>
</div>
<div id="tablist2" style="min-height: 400px;">
<div class="tablist block">
	<img src="/img/default/front/<?=$auth->locale?>/event_pic.jpg" width="198" height="198" class="event_detial_con_img" />
<div class="event_intr">
<p><?=$this->tr('EVENT_ORGANIZER')?>：<?=$this->detail ['fullname']?><br />
   <?=$this->tr('EVENT_DATE_RANGE')?>：<?=$this->detail ['deadline']?><br />
   <?=$this->tr('EVENT_PLACE')?>：<?=$this->detail ['place']?><br />
   <?=$this->tr('EVENT_NUMBER')?>：<?=$this->detail ['num']?><br />
   <?=$this->detail ['reply_num'].$this->tr('UNIT_ITEM') . $this->tr('EVENT_MESSAGE')?>  <span class="fred"><strong><?=$this->detail ['regist_num']?></strong></span> <?=$this->tr ( 'unit_person' ) . $this->tr('EVENT_SIGN_UP')?><br />
   <?$leaveDay = UtilService::dateDiff($this->detail ['deadline'], date('Y-m-d'), 'DAY')?>
   <?=$this->tr('EVENT_AWAY_FROM_EVENT_BEGIN')?> <span class="fred"><strong><?=$leaveDay > 0 ? $leaveDay : 0;?></strong></span> <?=$this->tr('UNIT_DAY')?></p>
<p>
<? if (empty($role)): ?>
	<a href="/front_register/register" class="agreen"><?=$this->tr('EVENT_REGISTER_MEMBER')?></a>
<? elseif ($code == $this->detail ['creator']) :?>
	<a href="/front_event/initiateevent/fid/<?=$this->detail ['id']?>" class="agreen">
		<img src="/img/default/front/<?=$auth->locale?>/btn_edit.jpg" width="80" height="34" align="middle" class="marR" id="updBtn"/>
	</a>
<? elseif ($role !== 'LP'):?>
	<img src="/img/default/front/<?=$auth->locale?>/btn_ent.jpg" width="100" height="34" align="middle" class="marR" id="regBtn"/>
<!--<? elseif ($role !== 'ADMIN' && $code != $this->detail ['creator']):?>
	<img src="/img/default/front/<?=$auth->locale?>/btn_edit.jpg" width="80" height="34" align="middle" class="marR" id="updBtn"/>-->
<? endif;?> 
</p>

<!--float 我要参加-->
<div class="floatdiv_event" id="enter_event" style="display: none">
<form id="form1" name="form1" method="post" action="" class="divForm">
<h3 class="floatdiv_event_t">
	<span class="fr">
	<a href="javascript:void(0);" name="cancelDiv">
		<img src="/img/default/front/<?=$auth->locale?>/icon_close.jpg" width="18" height="18" border="0" />
	</a></span><?=$this->tr('EVENT_JOIN')?>
</h3>
<div class="input_line">
	<label class="float_input_title"><?=$this->tr('EVENT_JOIN_NUMBER')?>：</label> 
	<input type="hidden" name="event_id" value="<?=$this->detail['id']?>"/>
	<input type="hidden" name="type" value="regist"/>
	<label><input type="text" name="regist_num" class="float_input" format="int"/></label>
</div>
<div class="input_line">
	<label class="float_input_title"><?=$this->tr('EVENT_MESSAGE')?>：</label> 
	<label><input type="text" name="content" class="float_input" /></label>
</div>
</form>
<div class="input_line">
	<label class="float_input_title">&nbsp;</label>
	<label> <input type="image" name="imageField2" src="/img/default/front/<?=$auth->locale?>/btn_tj.jpg" /> </label>
</div></div>

<!--float 取消参加-->
<div class="floatdiv_event" id="enter_dis" style="display: none">
<form id="form2" name="form2" method="post" action="" class="divForm">
<h3 class="floatdiv_event_t">
	<span class="fr">
	<a href="javascript:void(0);" name="cancelDiv">
		<img src="/img/default/front/<?=$auth->locale?>/icon_close.jpg" width="18" height="18" border="0" />
	</a></span><?=$this->tr('EVENT_CANCEL_JOIN')?>
</h3>
<div class="input_line">
	<label class="float_input_title"><?=$this->tr('EVENT_MESSAGE')?>：</label> 
	<input type="hidden" name="event_id" value="<?=$this->detail['id']?>"/>
	<input type="hidden" name="type" value="cancelRegist"/>
	<label><input type="text" name="content" class="float_input" /></label>
</div>
</form>
<div class="input_line">
	<label class="float_input_title">&nbsp;</label>
	<label> <input type="image" name="imageField2" src="/img/default/front/<?=$auth->locale?>/btn_tj.jpg" /> </label>
</div></div>
</div>
<br class="cls" />

<h3 class="tbg_grey01"><?=$this->tr('EVENT_CONTENT')?></h3>
<div class="f14 conU"><em><?=$this->tr('EVENT_POSTS').' '.$this->detail ['fullname'].' '.$this->tr('EVENT_POSTS_UPDATE_BY').' '.$this->detail ['update_time'].' '.$this->tr('EVENT_EDIT')?></em></div>
<div class="w720">
<span id="iframeValue" style="display: none"><?=$this->detail['content']?></span>
<iframe id="iframeTemp" src="" scrolling="no" frameborder="0" width="100%" height="100%" allowtransparency="true" /></iframe>
</div>
</div>

<div class="tablist">
<h3 class="tbg_grey01"><?=$this->tr('EVENT_MEMBER_LONG')?></h3>
<div class="event_people">
<ul>
	<?if(!empty($this->members)): foreach ($this->members as $member):?>
	<li><img src="/img/default/front/<?=$auth->locale?>/photo01.jpg"
		width="48" height="48" /><br />
	<?=$member['fullname']?></li>
	<?endforeach;endif;?>
</ul>
</div>
</div>
<div class="tablist">
<h3 class="tbg_grey01"><?=$this->tr('EVENT_MESSAGE')?></h3>
<div class="event_leave_word">
<form id="form3" name="form3" method="post" action="/front_event/reply">
<div class="item">
	<textarea rows="30" cols="50" name="content"></textarea>
	<script type="text/javascript">CKEDITOR.replace('content', {toolbar: 'Simple'});</script>
</div>
</form>
<label><input id="replyBtn" type="image" src="/img/default/front/<?=$auth->locale?>/btm_comment.jpg" class="marB" /></label>
<ul class="event_comment_detail" id="displayReplyList">
</ul>
<div class="pagination" id="Pagination">
</div>
</div></div></div></div>
<script type="text/javascript">
<!--
var loc = '<?=$auth->locale?>';
var EVENT_REPLY = '<?=$this->tr('EVENT_REPLY')?>';
var reload = true;
$(function() {
	fillIframe();
	$("#t1").click(function() {
		if ($(this).attr("class") == 'now') return false;
		$("#t1").addClass("now");
		$("#t2").removeClass("now");
		$("#t3").removeClass("now");
		$("#tablist2 div.tablist").removeClass("block");
		$("#tablist2 div.tablist").hide();
		$("#tablist2 div.tablist:eq(0)").show();
	});
	$("#t2").click(function() {
		if ($(this).attr("class") == 'now') return false;
		$("#t2").addClass("now");
		$("#t1").removeClass("now");
		$("#t3").removeClass("now");
		$("#tablist2 div.tablist").removeClass("block");
		$("#tablist2 div.tablist").hide();
		$("#tablist2 div.tablist:eq(1)").show();
	});
	$("#t3").click(function() {
		if ($(this).attr("class") == 'now') return false;
		$("#t3").addClass("now");
		$("#t1").removeClass("now");
		$("#t2").removeClass("now");
		$("#tablist2 div.tablist").removeClass("block");
		$("#tablist2 div.tablist").hide();
		$("#tablist2 div.tablist:eq(2)").show();
		loadReplyList();
	});
	var replyList;
	function loadReplyList() {
		replyList = $("#displayReplyList").pagingDisplay({
			url: "/front_event/searcheventreplylist?fid=<?=$this->detail ['id']?>",
			reload : reload,
			render: function(row) {
				var usrname = !!row['fullname'] ? row['fullname'] : "<?=$this->tr('EVENT_VISITOR')?>";
				var rst = '<img src="/img/default/front/'+loc+'/photo01.jpg" width="48" height="48" class="photo" /> ' + 
					'<div class="detail"> <p><span class="fr"><a href="#">'+EVENT_REPLY+'</a></span>' + 
					'<span class="fblue"><strong>'+usrname+'</strong></span> ' + 
					'<span class="fgrey">'+row['update_time']+'</span></p>'; 
//				if (row["regist_num"] > 0) {
//					rst = rst + '<p class="marB">最新参加人数如下，<span class="fred">请复制后添加自己再粘贴更新。</span></p>' 
//					rst = rst + '<p>8/16</p>';
//				}
				rst = rst + '<p>'+row['content']+'</p></div><br class="cls" />';
				return rst;
			}
		})
		reload = false;
	}
	function getTabIndex() {
		var currTab = $("#tab1 li.now").attr("id");
		if (currTab == 't3') return 3;
		else if (currTab == 't2') return 2;
		else return 1;
	}
	function fillIframe() {
		var content = $("#iframeValue").html();
		$("#iframeTemp").contents().find("body").append(content);
	}
	$("#regBtn").click(function() {
		$("#enter_event").show();
	});
	$("a[name='cancelDiv']").click(function() {
		$(this).parents("div.floatdiv_event").hide();
	});
	$("#replyBtn").click(function() {
		$.ajax({
			url: '/front_event/reply',
			type: 'post',
			async: false,
			dataType: 'json', //xml, json, script or html
			data: {'event_id': $("input[name='event_id']").val(),'content' : CKEDITOR.instances.content.getData()},
			success: function(data, textStatus, jqXHR) {
				if (data['err'] == 0) { 
					CKEDITOR.instances.content.setData("");
					$("#displayReplyList").pagingDisplay("reload");
				} else {
					alert(data['msg']);
				}
			}
		});
	})
	$("input[name='imageField2']").click(function() {
		var input = $(this);
		var form = input.parents("div.floatdiv_event").find("form.divForm")
		if (valForm(form)) {
			$.ajax({
				url: '/front_event/regist',
				type: 'post',
				async: false,
				dataType: 'json', //xml, json, script or html
				data: form.serializeArray(),
				success: function(data, textStatus, jqXHR) {
					if (data['err'] == 0) {
						loadReplyList();
						alert(data['msg'], $("#t3").click());
					} else {
						alert(data['msg']);
					}
				}
			});
		}
	})

	function valForm(ob) {
		var flag = true;
		$.each(ob.find("input[type='text']"), function() {
			if (!$(this).val()) {
				flag = false;
				return false;
			}
		})
		return flag;
	}

});
//-->
</script>
<script type="text/javascript" src="/js/jquery/jquery.pagination.js"></script>
<script type="text/javascript" src="/js/pagingDispaly.js"></script>

