<link href="/js/jquery/plupload/jquery.ui.plupload/css/jquery.ui.plupload.css" rel="stylesheet" type="text/css" />
<div>
	<form id="form_plupload" action="" target="_blank">
	    <div id="uploader" style="text-align:left; width:600px;">
	        <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
	    </div>
	    <div><button id="btn_upload">Upload</button></div>
	</form>

</div>


<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>
<script src="/js/jquery/plupload/plupload.full.js" type="text/javascript"></script>
<script src="/js/jquery/plupload/jquery.ui.plupload/jquery.ui.plupload.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
	// Convert divs to queue widgets when the DOM is ready
    $("#uploader").plupload({
        // General settings
        runtimes : 'gears,flash,silverlight,browserplus,html5',
        url : '/test_plupload/handleplupload',
        max_file_size : '10mb',
        chunk_size : '1mb',
        unique_names : true,
 
        // Resize images on clientside if we can
        resize : {width : 320, height : 240, quality : 90},
 
        // Specify what files to browse for
        filters : [
            {title : "Image files", extensions : "jpg,gif,png"},
            {title : "Zip files", extensions : "zip"}
        ],
 
        // Flash settings
        flash_swf_url : '/js/jquery/plupload/plupload.flash.swf',
 
        // Silverlight settings
        silverlight_xap_url : '/js/jquery/plupload/plupload.silverlight.xap'
    });

    
    // Client side form validation
    $('#form_plupload').submit(function(e) {
        var uploader = $('#uploader').plupload('getUploader');
        // Files in queue upload them first
        if (uploader.files.length > 0) {
            // When all files are uploaded submit form
            uploader.bind('StateChanged', function() {
                if (uploader.files.length === (uploader.total.uploaded + uploader.total.failed)) {
                	$('#form_plupload').submit();
                }
            });
            uploader.start();
        } else {
            alert('You must queue at least one file.');
        }
        return false;
    });


    $('#btn_upload').click(function() {
    	$('#form_plupload').submit();
    });
	
	
}); //$(document).ready

</script>