<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<h3 class="notice_t">
		<span id="msgBox" style="color: red; margin: 0 30px 0 0;">
		<?if ($auth->usr['role_code'] == 'LP') {
			echo $this->tr('SYS_MSG');
		} else {
			echo $this->tr('PERSONAL_MSG');
		}?>
		</span>
	<?php if ($auth->usr['role_code'] == 'MEMBER'):?>
		<span style="margin: 0 20px 0 0;">
			<a href="javascript:void(0);" id="btn_personalMsg"><?=$this->tr('PERSONAL_MSG')?></a>
		</span>
		<span>
			<a href="javascript:void(0);" id="btn_sysMsg"><?=$this->tr('SYS_MSG')?></a>
		</span>
	<?php endif;?>
		<!-- 隐藏变量：消息类型：个人消息或系统消息  -->
		<input type="hidden" id="msgType" value="PERSONAL" />
	</h3>
	<div id="tip_msg" class="tip"></div>
	<div id="msgList"></div>
	<div style="text-align: center; margin: 10px 0 0 0;">
		<a href="javascript:void(0)" id="btn_delMsg">
			<img src="/img/default/front/<?=$auth->locale?>/btn_msg_del.jpg" width="48" height="25" /> 
		</a>
	</div>
</div>


<script type="text/javascript">
	var roleCode = '<?=$auth->usr['role_code']?>';
	var SYS = '<?=$this->tr('SYS')?>';
	var SENDER = '<?=$this->tr('SENDER')?>';
	var SYS_MSG = '<?=$this->tr('SYS_MSG')?>';
	var PERSONAL_MSG = '<?=$this->tr('PERSONAL_MSG')?>';
	var TITLE = '<?=$this->tr('TITLE')?>';
	var RECEIVE_TIME = '<?=$this->tr('RECEIVE_TIME')?>';
	var CONFIRM_DEL = '<?=$this->tr('CONFIRM_DEL')?>';
</script>
<script src="/js/default/msg/msg/msg.js"></script>