<SCRIPT LANGUAGE="JavaScript">
window.onload = function() {
    doubleBgColor(document.getElementById("tab_list"),"#f3f3f3","#FFFFFF")
	doubleBgColor(document.getElementById("tab_list_end"),"#f3f3f3","#FFFFFF")
}

function doubleBgColor(Table,Bg1,Bg2) {
    for (var i=0;i<Table.rows.length;i++) Table.rows[i].bgColor=i%2?Bg2:Bg1;
}
</SCRIPT>
<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<form id="form1" name="form1" method="post" action="">
	<div class="search_result_lie01">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="tab_list" class="tab_search_list">
    <tr>
      <th width="7%" align="center">案件ID</th>
      <th width="19%" align="center">案件名</th>
      <th width="12%" align="center">应聘时间</th>
      <th width="12%" align="center">开始时间</th>
      <th width="12%" align="center">期间</th>
      <th width="14%" align="center">勤务地 </th>
      <th width="12%" align="center"> 单价/月 </th>
      <th width="12%" align="center">案件状态</th>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	 <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	<tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
    <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	<tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	<tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	<tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
	  <tr>
      <td align="center">A000001 </td>
      <td align="center" class="case_name">JAVA人员募集</td>
      <td align="center">2012-1-2 </td>
      <td align="center">2012-1-2 </td>
      <td align="center">3个月</td>
      <td align="center">东京，木场</td>
      <td align="center">40万</td>
      <td align="center">入场决定</td>
    </tr>
  </table>
  
</div>

<div class="btn_os">
  <label>
  <input type="image" name="imageField" src="/img/default/front/<?=$auth->locale?>/btn_ok.jpg" class="btn_marR" />
  </label>
  <label>
  <input type="image" name="imageField2" src="/img/default/front/<?=$auth->locale?>/btn_back.jpg" />
  </label>
  <div class="page"><span class="current">1</span>|<a href="#" target="_blank">2</a>|<a href="#" target="_blank">3</a>|<a href="#" target="_blank">4</a>|<a href="#" target="_blank">5</a>|<a href="#" target="_blank">次へ→</a></div>    
</div>
 </form>
</div>