<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript" src="/js/default/hdm.js"></script>
<div id="wraper">
	<div class="anchor">您现在的位置：管理员用户中心 > 邮件设定关联</div>
	<h3 class="t_top">邮件设定关联</h3>	
	<form id="form1" name="form1" method="post" action="">
	<div class="marB">
	  <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e5e5e5" class="tab_event">
        <tr>
          <th width="11%" align="right" bgcolor="#f7f7f7">&nbsp;</th>
          <th width="44%" align="center" bgcolor="#f7f7f7">动作</th>
          <th width="23%" align="center" bgcolor="#f7f7f7">管理员</th>
          <th width="22%" align="center" bgcolor="#f7f7f7">模板维护</th>
        </tr>
        <tr>
          <td rowspan="8" align="center" bgcolor="#FFFFFF">online</td>
          <td bgcolor="#FFFFFF">法人登录 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"> <a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">募集邀请（邀请法人员工）个人应聘此法人的案件</td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">法人（员工）应聘此法人的案件 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">管理员，营业员，法人面试调整</td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">管理员，营业员，法人面试决定  面试合格</td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">管理员发布消息</td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">所有取消，NG </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">录入人员录入完成 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td rowspan="6" align="center" bgcolor="#FFFFFF">BT</td>
          <td bgcolor="#FFFFFF">广告添加 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">可稼动人员列表 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">新增案件列表 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">时效性即将过期的案件（自己的案件） </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">新增用户 </td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF">新增法人</td>
          <td align="center" bgcolor="#FFFFFF"><label>
            <input type="radio" name="radiobutton" value="radiobutton" />
          </label></td>
          <td align="center" bgcolor="#FFFFFF"><a href="#" target="_blank">编辑</a></td>
        </tr>
      </table>
	 </div>
	</form>
</div>