<div id="wraper">
<?php
	$auth = new Zend_Session_Namespace('AUTH');
	if (isset($auth->usr) && $auth->usr["role_code"]=='LP') :
?>
<?php include_once 'inc/centerheader.phtml';?>
<? else :?>
<link href="/css/default/lp/css.css" rel="stylesheet" type="text/css" />
<? endif;?>
<div class="case_search_expand">
<h2 class="case_lie02_t"><span class="skim_num"><?=$this->tr("viewers")?><?=$this->case['viewers']?><?=$this->tr("unit_person")?></span><?=$this->case['name']?></h2>
<ul class="case_lie02_time">
	<li><?=$this->tr("case_release_date")?>：<?=$this->case["release_date"]?></li>
	<li><?=$this->tr("case_timeliness")?>：<?=$this->case["timeliness"]?></li>
	<li><?=$this->tr("case_lp_code")?>：<?=$this->case["lp_code"]?></li>
	<li><?=$this->tr("case_lp_name")?>：<?=$this->case["lp_name"]?></li>
</ul>
<div class="case_lie02_con">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
	<tr>
		<td colspan="2">【<?=$this->tr("case_business_req")?>】<?=$this->case["business_req"]?></td>
	</tr>
	<tr>
		<td colspan="2">【<?=$this->tr("case_technical_req")?>】<?=$this->case["technical_req"]?></td>
	</tr>
	<tr>
		<td width="40%">【<?=$this->tr("case_jpl")?>】<?=$this->case["jplValue"]?></td>
		<td width="60%">【<?=$this->tr("case_interview")?>】<?=$this->case["interviewerValue"]?></td>
	</tr>
	<tr>
		<td>【<?=$this->tr("case_case_range")?>】<?=$this->case["caseRangeValue"]?></td>
		<td>【<?=$this->tr("case_age_reg")?>】<?=$this->case["ageReqValue"]?></td>
	</tr>
	<tr>
		<td>【<?=$this->tr("case_end_range")?>　　】<?=$this->case["endDateValue"]?></td>
		<td>【<?=$this->tr("case_country_req")?>】<?=$this->case["countryReqValue"]?> </td>
	</tr>
	<tr>
		<td>【<?=$this->tr("case_delay")?>】<?=$this->case["delayValue"]?></td>
		<td>【<?=$this->tr("case_unit_price")?>　　】<?=$this->case["unitPriceValue"]?></td>
	</tr>
	<tr>
		<td>【<?=$this->tr("case_working_place")?>】<?=$this->case["workingPlaceValue"]?> </td>
		<td>【<?=$this->tr("case_overtime_pay")?>　　】<?=$this->case["overtimePayValue"]?></td>
	</tr>
</table>
</div>
</div>
<form action="" method="post" target="_self" id="form">
<input type="hidden" id="caseId" name="caseId" value="<?=$this->case['id']?>"/>
<input type="hidden" id="caseCode" name="caseCode" value="<?=$this->case['code']?>"/>
</form>

<? $show=!empty($this->caseType)?$this->caseType+0:123;
	$show = $show < 10 ? $show*10 : $show; 
	if ($show > 0) :?>
<div class="btn_center">
<?if ($show == 123 || ($show >= 10 && $show < 20)) :?>
	<label><input type="image" id="btn_editCase" src="/img/default/front/<?=$auth->locale?>/btn_case_edit.jpg" class="btn_marR" />
	</label>
<?endif;?>
<?if ($show == 123 || $show == 12 || ($show >= 20 && $show < 30)) :?>
	<label><input type="image" id="btn_caseApplyMgt" src="/img/default/lp/<?=$auth->locale?>/btn_manage.jpg" class="btn_marR" />
	</label>
<? endif;?>
<?if ($show == 13 || $show == 23 || $show >= 30) :?>
	<label><input type="image" id="btn_closeCase" src="/img/default/lp/<?=$auth->locale?>/btn_close.jpg" class="btn_marR" />
	</label>
<? endif;?>
</div> 
<? endif;?>
</div>

<script src="/js/default/lp/case/casedetail.js" type="text/javascript"></script>