<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<form id="form1" name="form1" method="post" action="">
 <h3 class="msg_title">法人关闭案件页面</h3>
 <div class="notice_con">你确定是否关闭下面的案件？</div>
 <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_del">
   <tr>
     <th width="25%">案件ID</th>
     <th width="75%" align="left"> 案件名 </th>
     </tr>
   <tr>
     <td align="center">A00002</td>
     <td align="left">JAVA人员招聘 </td>
     </tr>
   <tr>
     <td align="center">A00004</td>
     <td align="left">JAVA人员招聘 </td>
     </tr>
 </table>
 <div class="btn_center">
   <img src="/img/default/lp/<?=$auth->locale?>/btn_close.jpg" width="80" height="30" class="btn_marR" />
 </div>
  </form>
</div>