<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<form id="form1" name="form1" method="post" action="">
 <h3 class="msg_title">法人删除案件</h3>
 <div class="notice_con">你确定是否删除下面的案件？</div>
 <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_del">
   <tr>
     <th width="25%">案件ID</th>
     <th width="75%" align="left"> 案件名 </th>
     </tr>
   <tr>
     <td align="center">A00002</td>
     <td align="left">JAVA人员招聘 </td>
     </tr>
   <tr>
     <td align="center">A00004</td>
     <td align="left">JAVA人员招聘 </td>
     </tr>
 </table>
	<div class="btn_center">
		<a href="/lp_case/applycaselist" target="_blank">
			<img id="btn_delCase" src="/img/default/front/<?=$auth->locale?>/btn_case_del.jpg" width="80" height="30" class="btn_marR" />
		</a>
	</div>
  </form>
</div>

<script src="/js/default/lp/case/delcase.js" type="text/javascript"></script>