<link href="/css/default/lp/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<?php include_once 'inc/centerheader.phtml';?>
<div id="tab1">
	<div class="search_right">
		<a href="javascript:void(0)">
			<span class="case_lie_list" id="cases_expend"></span>
		</a>
		<span class="fblue"></span>
	</div>
	<h3 class="msg_title"><?=$this->tr('com_collect_case_list')?></h3>
</div>
<div class="user_case_list">
	<div id="caselist"></div>
</div>
<div class="btn_os">
<a href="javascript:void(0)" id="refuseBtn">
<img src="/img/default/front/<?=$auth->locale?>/btn_collection_refuse.jpg" width="80" height="30" class="btn_marR" />
</a>
</div>
<input type="button" id="searchBtn" style="display:none"/>
</div>

<script>
$(function() {
	var url = "/usr_casecollect/searchcomcollectcaselist";
	$("#caselist").ligerGrid({
		checkbox: true,
        columns: [{display: CASE_ID, name: 'code', width:65, render: CaseCodeFunction},
                  {display: CASE_NAME, name: 'name', render: CaseNameFunction},
                  {display: COL_A_INVITE_TIME, render: dateFunction, name: 'invite_date', width:73},
                  {display: case_end_range, name: 'period', width:110},
                  {display: WORKPLACE, name: 'workingPlaceValue', width:101},
                  {display: PRICE_UNIT_MONTHLY, name: 'unitPriceValueView', width:100},
                  {display: case_timeliness, name: 'timeliness', width:73},
                  {display: RELATION_OPERATE, render: opFunction, align: "center", width:100}],
        url: url,
        //height: "auto", 
        width: "100%",
        columnWidth: 270,
        isScroll: false, frozen:false,
        //rowHeight: 
        //headerRowHeight: 
        detail: {onShowDetail: showDetail, height: "auto"},
        pageSize: 20
    });
    var manager = $("#caselist").ligerGetGridManager();

    function CaseNameFunction(rowData, rowIndex) {
		return CaseNameFormatFunction(rowData, 'name', 'code');
	}
	function CaseCodeFunction(rowData, rowIndex) {
		return CaseCodeFormatFunction(rowData, 'code');
	}
    function dateFunction(rowData, rowIndex) {
		return DateFormatFunction(rowData, 'invite_date');
	}
    function opFunction(rowData, rowIndex) {
		return '<a href="javascript:void(0)" onclick="refuseCase('+null+',\''+rowData.code+'\',\''+rowData.name+'\',\''+rowData.invite_id+'\')">'+TITLE_CANCEL_INVITE+'</a>|<a href="javascript:void(0)" onclick="applyCase('+null+',\''+rowData.code+'\',\''+rowData.name+'\')">'+TITLE_APPLY+'</a>';
	}

    $("#searchBtn").click(function() {
		manager.loadServerData();
	})

	function showDetail(rowData, detailPanel) {
    	adjustCaseDetail(rowData);
		$(detailPanel).append($("#detail").html());
		$(detailPanel).find("#refuseBtn").click(function() {
			refuseCase([rowData]);
		});
		$(detailPanel).find("#applyBtn").click(function() {
			applyCase(rowData);
		});
		$(detailPanel).find("#viewDetail").click(function() {
			viewCase(rowData.code, "apply,refuse")
		});
	}

	$("#refuseBtn").click(function() {
		var rows = manager.getSelecteds();
		refuseCase(rows);
    	return false;
	})
	
	$("#cases_expend").toggle(function() {
		$(this).removeClass("case_lie_list").addClass("case_lie");
		expendDetailAll(manager, manager.getData().length);
	}, function() {
		$(this).removeClass("case_lie").addClass("case_lie_list");
		collapseDetailAll(manager, manager.getData().length);
	})
})
function refuseCase(rows, caseCode, caseName, invite_id) {
	if ((!rows || rows.length == 0) && !caseCode && !caseName) {
		alert(PLEASE_CHOISE_CANCEL_INVITE_CASE);
		return false;
	}
	rows = rows || [{code: caseCode, name: caseName, invite_id: invite_id}];
	var html = ['<div style="width:500px;"><div class="notice_con">'+SURE_CANCEL_INVITE_CHOOSE_CASE+'</div>'];
	html.push('<table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_del">');
	html.push('<tr>');
	html.push('<th width="25%">'+CASE_ID+'</th>');
	html.push('<th width="75%" align="left"> '+CASE_NAME+' </th>');
	html.push('</tr>');
	$.each(rows, function(i, v) {
		html.push('<tr>');
		html.push('<th width="25%">'+v.code+'</th>');
		html.push('<th width="75%" align="left"> '+v.name+' </th>');
		html.push('</tr>');
	});
	html.push('</table>');
	html.push('</div>');
	html = html.join("");
	ligerConfirm(TITLE_CANCEL_INVITE, html, {width: 550}, function() {
		var ids = "";
		$.each(rows, function(i, v) {
			ids += v.invite_id;
			ids += ",";
		});
		ids = ids.substring(0, ids.length-1);
		$.ajax({
			url: '/usr_casecollect/valrefusecase',
			type: 'post',
			async: false,
			dataType: 'json', //xml, json, script or html
			data: {ids: ids},
			success: function(data, textStatus, jqXHR) {
				if (data['err'] == 0) {
					$("#dynForm").attr("action", "/usr_casecollect/refusecollectcase");
					$("#dynForm #ids").val(ids);
					$("#dynForm").submit();
				} else {
					alert(data['msg']);
				}
			}
		});
		return false;
	});
}
</script>

<form id="dynForm" style="display:none;" method="post" target="_blank">
<input id="caseId" name="caseId"/>
<input id="btnlist" name="btnlist"/>
<input id="applyId" name="applyId"/>
<input id="ids" name="ids"/>
</form>

<div id="detail" style="display: none;">
<div class="case_search_expand">
<h2 class="case_lie02_t"><span class="skim_num"><?=$this->tr("viewers")?><span id="viewers"></span><?=$this->tr("unit_person")?></span><span id="name"></span></h2>
<ul class="case_lie02_time">
<li><?=$this->tr("UPDATE_DATE")?>：<span id="last_modify_time" format="date"></span></li>
<li><?=$this->tr("case_timeliness")?>：<span id="timeliness"></span></li>
</ul>
<div class="case_lie02_con">
	<table style="width:100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
	<tr>
		<td width="8%" align="left" valign="top">【<?=$this->tr("case_business_req")?>】</td>
		<td colspan="4"><span id="business_req"></span></td>
	</tr><tr>
		<td width="8%" align="left" valign="top">【<?=$this->tr("case_technical_req")?>】</td>
		<td colspan="4"><span id="technical_req"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_jpl")?>】</td>
		<td width="31%"><span id="jplValue"></span></td>
		<td width="9%" align="left">【<?=$this->tr("case_interview")?>】</td>
		<td width="37%"><span id="interviewerValue"></span></td>
		<td width="13%" rowspan="5" align="center">
		<a href="javascript:void(0)" id="refuseBtn">
			<img src="/img/default/front/<?=$auth->locale?>/btn_collection_refuse.jpg" width="80" height="30" border="0" class="marB" />
		</a><br />
		<a href="javascript:void(0)" id="applyBtn">
			<img src="/img/default/front/<?=$auth->locale?>/btn_offer.jpg" width="80" height="30" border="0" class="marB" />
		</a><br />
		<a href="javascript:void(0)" id="viewDetail">
			<img src="/img/default/front/<?=$auth->locale?>/btn_look_detail.jpg" width="80" height="30" border="0" />
		</a></td>
	</tr><tr>
		<td>【<?=$this->tr("case_case_range")?>】</td><td><span id="caseRangeValue"></span></td>
		<td>【<?=$this->tr("case_age_reg")?>】</td><td><span id="ageReqValue"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_end_range")?>　　】</td><td><span id="period"></span></td>
		<td>【<?=$this->tr("case_country_req")?>】</td><td><span id="countryReqValue"></span> </td>
	</tr><tr>
		<td>【<?=$this->tr("case_delay")?>】</td><td><span id="delayValue"></span></td>
		<td>【<?=$this->tr("case_unit_price")?>　　】</td><td><span id="unitPriceValueView"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_working_place")?>】</td><td><span id="workingPlaceValue"></span> </td>
		<td>【<?=$this->tr("case_overtime_pay")?>　　】</td><td><span id="overtimePayValue"></span></td>
	</tr>
</table>
</div></div></div>
<script type="text/javascript" src="/js/default/front/case/caseutil.js"></script>