<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>

<link href="/css/default/front/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<div class="title_img"><img src="/img/default/front/<?=$auth->locale?>/title_ouradvantage.jpg" width="960" height="148" /></div>
<h3 class="our_advantage_t">为什么选择人才案件导航网</h3>
<div class="c_advantage">人才按键导航网是日本第一家专业针对在日技术者的网站，这里拥有最直接的客户，最新，最有效，单价最高的案件，同时拥有全日本最优秀的技术者。我们提供一对一全程服务，为您找到最合适的案件，最合适的人才，使您的价值发挥到最高。</div>
<h3 class="tbg_grey"><span class="fr"><a href="/front_register/register" target="_blank">
	<img src="/img/default/front/<?=$auth->locale?>/btn_register_person.jpg" width="99" height="24" border="0" />
</a></span>个人</h3>
<div class="c_advantage">
  <p class="fblue"><strong>1.海量案件供您应聘</strong></p>
  <p>    您可以查询选择自己感兴趣的案件，进行应聘，并且及时追踪应聘情况。</p>
  <p class="fblue"><strong>    2.最快速找到合适的案件</strong></p>
  <p>当您更新您的简历状态，会有数十家公司同时阅览您的匿名简历，任何一家公司可以直接调整面试，使您最快速找到合适的案件。</p>
  <p class="fblue"><strong> 3.了解即时的案件信息</strong></p>
  <p> 当您选择邮件订阅服务，您可以每日收到与您相关的案件，使您及时了解到案件情况。</p>
  <p class="fblue"><strong>    4.最前沿的技术讨论</strong></p>
  <p>    技术论坛拥有大批优秀技术者，他们及时解决您的技术疑难问题，并且您可以分享大家的最新技术。</p>
</div>
<h3 class="tbg_grey"><span class="fr">
	<a href="/front_lpreg/lpreg" target="_blank">
		<img src="/img/default/front/<?=$auth->locale?>/btn_register_faren.jpg" width="99" height="24" border="0" />
	</a></span>法人
</h3>
<div class="c_advantage">
	<p class="fblue"><strong>1.检索合适人才</strong></p>
  <p>根据您的案件要求，可以在本网站检索出适合您案件的合适人才，并且进行面试。</p>
  <p class="fblue"><strong>2.最短时间找到合适的技术者</strong></p>
  <p>人才案件导航网拥有大批优秀技术者，当您发布案件之后，会直接发送给技术者，技术者可以通过本网站直接应聘，也可以介绍朋友来应聘您的案件。使您在最短时间内找到合适的技术者。</p>
  <p class="fblue"><strong>3.帮您公司技术者找到合适的案件</strong></p>
  <p>您可以在本网站找到适合您公司技术者的案件，进行提案。</p>	
</div>
</div>
