<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
<h3 class="msg_title">基本设定→会员情报设定</h3>
  <div class="con_faren_center">
    <h3 class="note_t">员工ID：00001</h3>
	<h3 class="note_t">简历设定</h3>
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <th width="22%" align="right" bgcolor="#f7f7ff">基本情报：</th>
            <td width="78%" bgcolor="#f7f7ff"><span class="btn_bg"><a href="#" target="_self">更 改</a></span>出生年月日，居住地，最终学历等修改</td>
          </tr>
          <tr>
            <th align="right" bgcolor="#f7f7ff">经验语言：</th>
            <td bgcolor="#f7f7ff"><span class="btn_bg"><a href="#" target="_self">更 改</a></span>技术经验修改</td>
          </tr>
          <tr>
            <th align="right" bgcolor="#f7f7ff">项目经历：</th>
            <td bgcolor="#f7f7ff"><span class="btn_bg"><a href="#" target="_self">更 改</a></span>项目经历修改</td>
          </tr>
        </table>
		<h3 class="note_t">其他设定</h3>	
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <th width="22%" align="right" valign="top" bgcolor="#f7f7ff">其他信息：</th>
            <td width="78%" bgcolor="#f7f7ff">
			  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_info_set">
                <tr>
                  <td width="52%">可稼动日：20120301<br />
                    营业状态：并行营业有<br />
                    希望单价：50万/月<br />
                    最低提案可单价：30万/月<br />
                    希望工作地点：关东<br />
                  期望项目形态：三个月以上</td>
                  <td width="48%"><span class="btn_bg"><a href="#" target="_self">更 改</a></span></td>
                </tr>
              </table></td>
          </tr>
          <tr>
            <th align="right" bgcolor="#f7f7ff">备注：</th>
            <td bgcolor="#f7f7ff">此人性格开朗</td>
          </tr>
        </table>
		<h3 class="note_t">简历公开设定</h3>	
	    <table width="100%" border="0" cellpadding="0" cellspacing="1" bgcolor="#e6e6f4" class="tab_info">
          <tr>
            <th width="22%" align="right" bgcolor="#f7f7ff">是否公开：</th>
            <td width="39%" bgcolor="#f7f7ff"><label>
              <input type="radio" name="radiobutton" value="radiobutton" />
            公开&nbsp;&nbsp;
            <input type="radio" name="radiobutton" value="radiobutton" />
            否&nbsp;&nbsp;</label></td>
            <td width="39%" bgcolor="#f7f7ff"><span class="btn_bg"><a href="#"  target="_self">更 改</a></span>
		</td>
          </tr>
        </table>
  </div>
</div>
