<div id="wraper">
	<?php include_once 'inc/centerheader.phtml';?>
	<h3 class="msg_title">法人员工检索</h3>
	  <div class="case_search_con">
		  <select name="select2" class="select_w160">
		    <option>姓名</option>
	      </select>
		  <input type="text" name="textfield" class="myinput_w360" />
		  <a href="/lp_emp/empsearchresult" target="_blank">
		  	<img alt="检索" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" />
		  </a>
	  </div>
	<div class="c_case_search">
	<form id="form2" name="form2" method="post" action="">
		
		<h4 class="case_search_title">选择OS</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="19%">
                
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                
                Windows</td>
              <td width="23%">
                <input type="checkbox" name="checkbox8" value="checkbox" />
                linux,Unix </td>
              <td width="58%">
                <input type="checkbox" name="checkbox6" value="checkbox" />
              Android</td>
            </tr>
            <tr>
              <td>
                <input type="checkbox" name="checkbox3" value="checkbox" />
                Iphone</td>
              <td>
                <input type="checkbox" name="checkbox9" value="checkbox" />
                              OS390</td>
              <td>
                <input type="checkbox" name="checkbox12" value="checkbox" />
              其它</td>
            </tr>
          </table>
		</div>
		<div class="fl w01">
		<h4 class="case_search_title">选择经验语言/FrameWork(N年以上)</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="28%">
                
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                
                JAVA</td>
              <td width="15%" align="left" valign="middle">
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td width="39%">
                <input type="checkbox" name="checkbox8" value="checkbox" />
                C/C++/VC++</td>
              <td width="18%">
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><input type="checkbox" name="checkbox3" value="checkbox" /> COBOL</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td><input type="checkbox" name="checkbox9" value="checkbox" /> .NET（c#/VB/ASP）</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><input type="checkbox" name="checkbox4" value="checkbox" /> PHP</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td><input type="checkbox" name="checkbox10" value="checkbox" /> SAP/ABAP</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>

              <td><input type="checkbox" name="checkbox5" value="checkbox" /> Struts</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td><input type="checkbox" name="checkbox11" value="checkbox" /> EJB</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><input type="checkbox" name="checkbox26" value="checkbox" /> Intra-mart</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td><input type="checkbox" name="checkbox27" value="checkbox" /> Terasoruna</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td><input type="checkbox" name="checkbox7" value="checkbox" /> 其他</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table>
		</div>
	  </div>
		<div class="fr w02">
		<h4 class="case_search_title">选择业务领域(N年以上)</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="26%">
                
                  <input type="checkbox" name="checkbox2" value="checkbox" />
                
                证券</td>
              <td width="24%">
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td width="25%">
                <input type="checkbox" name="checkbox8" value="checkbox" />
                银行</td>
              <td width="25%">
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td>
                <input type="checkbox" name="checkbox3" value="checkbox" />
                保险</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td>
                <input type="checkbox" name="checkbox9" value="checkbox" />
                流通</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td>
                <input type="checkbox" name="checkbox4" value="checkbox" />
                人事</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td>
                <input type="checkbox" name="checkbox10" value="checkbox" />
                经理</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
            <tr>
              <td>
                <input type="checkbox" name="checkbox5" value="checkbox" />
                携带</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
              <td>
                <input type="checkbox" name="checkbox11" value="checkbox" />
                其它</td>
              <td>
                <select name="select" class="select_year">
                  <option>1年</option>
                </select>
              </td>
            </tr>
          </table>
		</div>
	  </div>
		<br class="cls" />
		<h4 class="case_search_title">选择勤务地</h4>
		<div class="address_t">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><input type="checkbox" name="checkbox13" value="checkbox" />		日本 </td>
            </tr>
          </table>
		</div>
		<div class="address_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td>
                <input type="checkbox" name="checkbox14" value="checkbox" />
                北海道</td>
              <td>
                <input type="checkbox" name="checkbox15" value="checkbox" />
                东北</td>
              <td>
                <input type="checkbox" name="checkbox16" value="checkbox" />
                关东              </td>
              <td>
                <input type="checkbox" name="checkbox17" value="checkbox" />
                东海</td>
              <td>
                <input type="checkbox" name="checkbox18" value="checkbox" />
                北信越</td>
            </tr>
            <tr>
              <td>
                <input type="checkbox" name="checkbox19" value="checkbox" />
                关西</td>
              <td>
                <input type="checkbox" name="checkbox20" value="checkbox" />
                中国.四国</td>
              <td>
                <input type="checkbox" name="checkbox21" value="checkbox" />
                九州.冲绳</td>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
          </table>
		</div>
		<div class="address_t">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td><input type="checkbox" name="checkbox13" value="checkbox" />		海外 </td>
            </tr>
          </table>
		</div>
		<div class="address_con">
		  <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tab_case_search">
            <tr>
              <td width="19%">
                <input type="checkbox" name="checkbox22" value="checkbox" />
                 中国</td>
              <td width="23%">
                <input type="checkbox" name="checkbox23" value="checkbox" />
                其他</td>
              <td width="22%">&nbsp;</td>
              <td width="16%">&nbsp;</td>
              <td width="20%">&nbsp;</td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title">其他条件</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr>
              <td width="27%">性  别
                
                <input type="radio" name="radiobutton" value="radiobutton" />
              男
              <input type="radio" name="radiobutton" value="radiobutton" />
              女</td>
              <td width="73%">年龄
                
                <select name="select4" class="select_w60">
                </select>
              ～
              <select name="select5" class="select_w60">
              </select>
              </td>
            </tr>
            <tr>
              <td>日本语
                
                <select name="select3" class="select_w160">
                  <option>必要的最低限会话可</option>
                </select>
              </td>
              <td>&nbsp;</td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title">稼动可日期</h4>
		<div class="case_search_con">
		  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search">
            <tr>
              <td width="9%">
                <input type="radio" name="radiobutton" value="radiobutton" />
              即日</td>
              <td width="91%">
                <input type="radio" name="radiobutton" value="radiobutton" />
              <input class="Wdate" type="text" onClick="WdatePicker()">～<input class="Wdate" type="text" onClick="WdatePicker()"></td>
            </tr>
          </table>
		</div>
		<h4 class="case_search_title">单价</h4>
		<div class="case_search_con"><input type="text" name="textfield2" class="search_input_time" />
		以下</div>
		<div class="btn_search"><a href="/lp_emp/empsearchresult" target="_blank"><img src="/img/default/front/<?=$auth->locale?>/btn_search.jpg" width="191" height="38" border="0" /></a></div>
	</form>
	</div>
</div>