<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<script language="javascript" type="text/javascript"
	src="/js/default/hdm.js"></script>
<div id="wraper">
<h3 class="t_top"><?=$this->tr('edit_editor')?></h3>
<form id="form1" name="form1" method="post" action="">
<div class="info_modify">
<table width="100%" border="0" cellspacing="0" cellpadding="0" class="tab_info_modify">
	<tr>
		<td width="137" align="right"><?=$this->tr('editor_id')?>：</td>
		<td width="313"><input type="text" name="sid" class="myinput" alt="<?=$this->tr('editor_id_cannot_be_null')?>" value="<?=$this->editor['email']?>"/></td>
	</tr>
	<tr>
		<td align="right"><?=$this->tr('editor_name')?>：</td>
		<td><input type="text" name="username" class="myinput" alt="<?=$this->tr('editor_name_cannot_be_null')?>" value="<?=$this->editor['fullname']?>"/></td>
	</tr>
	<tr>
		<td align="right"><?=$this->tr('editor_password')?>：</td>
		<td><input type="password" name="password" class="myinput" alt="<?=$this->tr('editor_password_cannot_be_null')?>" value=""/></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><a href='javascript:void(0)' id='submitBtn'><img src="/img/default/front/<?=$auth->locale?>/btn_qd.jpg" class="marR" /></a></td>
	</tr>
</table>
</div>
</form>
</div>
<script>
$(function() {
	$("#submitBtn").click(function() {
		if (valErr()) {
			$.ajax({
				url: '/admin/admin_editor/saveediteditor',
				type: 'post',
				async: false,
				dataType: 'json',
				data: $('#form1').serializeArray(),
				success: function(data, textStatus, jqXHR) {
					if (data['err'] == 0) {
						var url = "/admin/admin_editor/editorlist"
						alert(data['msg'], null,null, window.location.href = url);
					} else {
						if (!!data["errField"] && $("#"+data["errField"]).length > 0) {
							$("#"+data["errField"]).focus();
							$("#"+data["errField"]).showError(data['msg']);
						} else {
							alert(data['msg']);
						}
					}
				}
			});
		}
	})

	function valErr() {
		var flag = true;
		$.each($("table.tab_info_modify").find("input[type='text']"), function() {
			if (!$(this).val()) {
				alert($(this).attr("alt"));
				flag = false;
				return false;
			}
		})
		return flag;
	}
})
</script>