<?php 
	$auth = new Zend_Session_Namespace('AUTH');
?>
<link href="/css/default/lp/css.css" rel="stylesheet" type="text/css" />
<div id="wraper">
<div id="tablist1">
	<div class="case_search">
	<div class="search_left">
		<img src="/img/default/lp/<?=$auth->locale?>/icon_list_search.jpg" width="28" height="23" class="icon_search" />
		<select id="range" name="range" class="myselect">
			<option value="all"><?=$this->tr("case_all")?></option>
			<option value="code"><?=$this->tr("case_id")?></option>
			<option value="name"><?=$this->tr("case_name")?></option>
		</select>
		<label><input type="text" id="caseName" class="myinput" /></label>
		<label><input type="checkbox" name="checkbox" value="checkbox" /> <?=$this->tr("interview_has")?> </label>
		<input type="image" id="searchBtn" src="/img/default/front/<?=$auth->locale?>/btn_jiansuo.jpg" />
	</div>
	<div class="search_right">
		<a href="javascript:void(0)">
			<span class="case_lie_list" id="cases_expend"></span>
		</a>
	</div>
	</div>
</div>

<div id="tbl1" class="search_result_lie01">
	<div id="caseinlist"></div>
</div>
</div>

<script>
var manager; 
$(function() {
	var inurl = "/lp_casecollect/searchreleasecases";

	function loadTab1() {
	    $("#caseinlist").ligerGrid({
	        columns: [{display: CASE_ID, name: 'code', width:70},
	                  {display: CASE_NAME, name: 'name'},
	                  {display: case_business_req, name: 'businessReqValue'},
	                  {display: case_technical_req, name: 'technicalReqValue'},
	                  {display: case_startdate, name: 'startDateValue', width:73},
	                  {display: case_end_range, name: 'period', width:77},
	                  {display: WORKPLACE, name: 'workingPlaceValue', width:100},
	                  {display: PRICE_UNIT_MONTHLY, name: 'unitPriceValue', width:95},
	                  {display: case_timeliness, name: 'timeliness', width:80},
	                  {display: RELATION_OPERATE, render: opFunction, align: "center", width:65}],
	        url: inurl,
	        //height: "auto", 
	        width: "100%",
	        columnWidth: 120,
	        isScroll: false, frozen:false,
	        //rowHeight: 
	        //headerRowHeight: 
	        detail: {onShowDetail: showDetail, height: "auto"},
	        pageSize: 20
	    });
	    manager = $("#caseinlist").ligerGetGridManager();
	}
	loadTab1();

    $("#searchBtn").click(function() {
		var caseName = $("#caseName").val();
		var range = $("#range").val();
		manager.loadServerData({"casename": caseName, "range": range});
    });

	function opFunction(rowData, rowIndex) {
    	return '<a onclick="inviteCase(null, \''+rowData.code+'\')" href="javascript:void(0)">'+TITLE_INVITE+'</a>';
    }

	function showDetail(rowData, detailPanel) {
		adjustCaseDetail(rowData)
		$(detailPanel).append($("#detail").html());
		$(detailPanel).find("#inviteBtn").click(function() {
			inviteCase([rowData]);
		});
	}

	$("#closeBtn1").click(function() {
    	var rows = manager.getSelecteds();
    	closeCase(rows);
    	return false;
    });
    
	$("#cases_expend").toggle(function() {
		$(this).removeClass("case_lie_list").addClass("case_lie");
		expendDetailAll(manager, manager.getData().length);
	}, function() {
		$(this).removeClass("case_lie").addClass("case_lie_list");
		collapseDetailAll(manager, manager.getData().length);
	})
});
function editCase(id) {
	$("#dynForm").attr("action", "/front_case/casedetail");
	$("#dynForm").find("#caseId").val(id);
	if($("#tbl3:hidden").length > 0) 
		$("#dynForm").find("#btnlist").val("edit,caseApplyMgt,close");
	else 
		$("#dynForm").find("#btnlist").val("");	
	$("#dynForm").submit();
}

function managerCase(id) {
	$("#dynForm").attr("action", "/lp_caseapply/caseapplymgt");
	$("#dynForm").find("#caseId").val(id);
	$("#dynForm").submit();
}

function inviteCase(rows, caseCode) {
	if ((!rows || rows.length == 0) && !caseCode) {
		alert(PLEASE_CHOISE_INVITE_CASE);
		return false;
	}
	rows = rows || [{code: caseCode}];
	ligerConfirm(TITLE_INVITE, SURE_CHOISE_INVITE_CASE, {width: 550}, function() {
		var ids = "";
		$.each(rows, function(i, v) {
			ids += v.code;
			ids += ",";
		});
		ids = ids.substring(0, ids.length-1);
		$("#dynForm").attr("action", "/front_invite/chooseinvitecaseconfirm");
		$("#dynForm").find("#caseCode").val(ids);
		$("#dynForm").submit();
	});
}
</script>

<div id="detail" style="display: none;">
<div class="case_search_expand">
<h2 class="case_lie02_t"><span class="skim_num"><?=$this->tr("viewers")?><span id="viewers"></span><?=$this->tr("unit_person")?></span><span id="name"></span></h2>
<ul class="case_lie02_time">
<li><?=$this->tr("UPDATE_DATE")?>：<span id="last_modify_time" format="date"></span></li>
<li><?=$this->tr("case_timeliness")?>：<span id="timeliness"></span></li>
<li style="display: none"><?=$this->tr("case_lp_code")?>：<span id="lp_code"></span></li>
<li style="display: none"><?=$this->tr("case_lp_name")?>：<span id="lp_name"></span></li>
</ul>
<div class="case_lie02_con">
	<table style="width:100%" border="0" cellspacing="0" cellpadding="0" class="tab_case_search_lie02">
	<tr>
		<td width="8%" align="left" valign="top">【<?=$this->tr("case_business_req")?>】</td>
		<td colspan="4"><span id="business_req"></span></td>
	</tr><tr>
		<td width="8%" align="left" valign="top">【<?=$this->tr("case_technical_req")?>】</td>
		<td colspan="4"><span id="technical_req"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_jpl")?>】</td>
		<td width="31%"><span id="jplValue"></span></td>
		<td width="9%" align="left">【<?=$this->tr("case_interview")?>】</td>
		<td width="37%"><span id="interviewerValue"></span></td>
		<td width="13%" rowspan="5" align="center">
		<a href="javascript:void(0)" id="inviteBtn">
			<img src="/img/admin/<?=$auth->locale?>/btn_invite.gif" width="80" height="30" border="0" class="marB" />
		</a></td>
	</tr><tr>
		<td>【<?=$this->tr("case_case_range")?>】</td><td><span id="caseRangeValue"></span></td>
		<td>【<?=$this->tr("case_age_reg")?>】</td><td><span id="ageReqValue"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_end_range")?>　　】</td><td><span id="period"></span></td>
		<td>【<?=$this->tr("case_country_req")?>】</td><td><span id="countryReqValue"></span> </td>
	</tr><tr>
		<td>【<?=$this->tr("case_delay")?>】</td><td><span id="delayValue"></span></td>
		<td>【<?=$this->tr("case_unit_price")?>　　】</td><td><span id="unitPriceValueView"></span></td>
	</tr><tr>
		<td>【<?=$this->tr("case_working_place")?>】</td><td><span id="workingPlaceValue"></span> </td>
		<td>【<?=$this->tr("case_overtime_pay")?>　　】</td><td><span id="overtimePayValue"></span></td>
	</tr>
</table>
</div></div></div>

<form id="dynForm" style="display:none;" method="post">
<input id="resumeCodes" name="resumeCodes" value='<?=$this->resumeCodes?>'/>
<input id="caseCode" name="caseCode"/>
</form>